import { Page, Locator } from '@playwright/test';

export class CommonPage_Public {
	page: Page;
  breadcrumbsSections: Locator;
  journalsMouseHoverLink: Locator;
  journalsLink: Locator;
  stpLinkInSideNav: Locator;
  manualsLinkInSideNav: Locator;
  storeLogo: Locator;
  MemupdatecompleteComment: Locator;
  ebsNumber: Locator;
  mcsButton: Locator;
  accountButtonStatus: Locator;
  languageLink: Locator;
  contactLink: Locator;
  cartLink: Locator;
  policiesLink: Locator;
  emailSubscriptionSettingsLink: Locator;
  privacyPolicyLink: Locator;
  getInvolved1: Locator;
  anniversary: Locator;
  ConsumerParticipation: Locator;
  ConsumerParticipation_dropdownValues: Locator;
  anniversary_dropdownValues: Locator;
  dropdownValues: (value: number) => Locator;
  personalcerification: Locator;
  learnmoreunderpersonalcerification: Locator;
  SignInLink: Locator;
  signInLink: Locator;
  signInDropDown: Locator;
  signInLinkUnderDropDown: Locator;
  signInButton: Locator;
  createAccountButton: Locator;
  continueButton: Locator;
  addContinue: Locator;
  saveButton: Locator;
  AddAttributePageSaveBtn: Locator;
  ProductPurchaseBtn: Locator;
  saveCustomerButton: Locator;
  saveCustomerBTN: Locator;
  saveBillingReplationshipBTN: Locator;
  saveAndContinueEdit: Locator;
  checkboxdropdown: Locator;
  AddressValidationHeader: Locator;
  AddressValContinueBtn: Locator;
  ebsOrderStatus: Locator;
  MAEOrderStatus: Locator;
  OrderType: Locator;
  selectAllcheckbox: Locator;
  addnewaddress: Locator;
  loginLink: Locator;
  myASTMLink: Locator;
  addproductSKU: Locator;
  SKUnumberTextbox: Locator;
  QuantityTextbox: Locator;
  contact: Locator;
  serpFirstDoc: Locator;
  closepopup_firsttime: Locator;
  addProductBtn: Locator;
  addskunumber: Locator;
  addEbsSku: Locator;
  AddAnotherBtn: Locator;
  AddToOrderBtn: Locator;
  startDate1: Locator;
  startDateInput: Locator;
  publishDateInput: Locator;
  publishDateInput2: Locator;
  startDateInput2: Locator;
  startDate2: Locator;
  GoToday: Locator;
  closebtn: Locator;
  publishDate1: Locator;
  publishDate2: Locator;
  checkBox: Locator;
  searchgridBtn: Locator;
  addqty: Locator;
  addtoOrderbutton: Locator;
  AddressDescriptionLabel: Locator;
  contactBillingAddress: Locator;
  ContactBillingAddressValidation: Locator;
  contactShippingAddress: Locator;
  ContactShippingAddressValidation: Locator;
  AddressInformationLabel: Locator;
  StreetAddressLabel: Locator;
  selectContactBillingAddress: Locator;
  selectContactShippingAddress: Locator;
  majorpromocode: Locator;
  minorpromocode: Locator;
  orderchannel: Locator;
  submitorderButton: Locator;
  SubmitOrderBottom: Locator;
  SubmitorderPopupOkBtn: Locator;
  addSelectedProduct: Locator;
  eMailAddress: Locator;
  CommunicationEmail: Locator;
  OrganizationName: Locator;
  searchButton: Locator;
  publicSearchButton: Locator;
  selectsearchedcustomer: Locator;
  enterEmail: Locator;
  enterCommunicationEmail: Locator;
  firstName: Locator;
  lastName: Locator;
  phoneNumber: Locator;
  phonenumber: Locator;
  zipcode: Locator;
  streetaddress: Locator;
  country: Locator;
  state: Locator;
  city: Locator;
  onlineSubscriptions: Locator;
  astmLogo: Locator;
  TelephoneNo: Locator;
  SaveCustomer: Locator;
  apiLogo: Locator;
  searchCombobox: Locator;
  EnvironmentalProductDeclarations: Locator;
  searchIcon: Locator;
  informationTab: Locator;
  searchASTM: Locator;
  searchhowtogetinvolved: Locator;
  searchASTMinsightSQC: Locator;
  searchMarketintelligence: Locator;
  footerSearchIcon: Locator;
  searchResults: Locator;
  searchResultsCMSInfo: Locator;
  searchResultsPAndS: Locator;
  footerReadingRoom: Locator;
  requestDemo1: Locator;
  requestDemo2: Locator;
  joinNow: Locator;
  standardbycategory: Locator;
  headerSearchDropdown: Locator;
  copydesignation: (no: number) => Locator;
  nocommitteeaffiliation: Locator;
  transportablemoisturelimitofcoal: Locator;
  productsAndServices: Locator;
  productsAndServicesNavigation: Locator;
  StandardsAndSolutionsNew: Locator;
  standardsAnsSolutionsInCartPage: Locator;
  productsAndServicesNavigationMobile: Locator;
  marketintelligence: Locator;
  petrolumreferencematerial: Locator;
  wohlersreport: Locator;
  wohlerassociatelink: Locator;
  marketintelligenceHeader: Locator;
  wohlersreportHeader: Locator;
  petroleumreferencematerialVideo: Locator;
  petroleumreferencematerialfooterheading: Locator;
  petroleumreferencematerialfootercontactUs: Locator;
  unlimitedaccessnowavailable: Locator;
  learnmoreaboutASTMrefmats: Locator;
  marketintelligenceotherheadings: Locator;
  contactUsundermarketintelligence: Locator;
  contactUsunderwohlerreport: Locator;
  learnmoreaboutwohlersbutton: Locator;
  learnmoreaboutwohlersimage: Locator;
  membershipHeader: Locator;
  participatingHeader: Locator;
  standardsAndPublicationsOptions: Locator;
  standardsAndSolutions: Locator;
  signOutMenu: Locator;
  signOutLink: Locator;
  LaboratoryServicesOptions: Locator;
  BookfStandardsOptions: Locator;
  fontenotmaillink: Locator;
  phoneNoUnderdvisoryservices: Locator;
  phoneNoUndercontactustodayforallyourAMconsultingneeds: Locator;
  ptpmailLink: Locator;
  PTPShippingPolicy: Locator;
  fontenotphonenumber: Locator;
  standardsProducts: Locator;
  technicalReports: Locator;
  wohlerimage: Locator;
  bookOfStandardsOptions: Locator;
  annualBookOfStandards: Locator;
  readingRoomOptions: Locator;
  readingRoomInSAndP: Locator;
  trackerServicesOptions: Locator;
  catalogsOptions: Locator;
  standardsAndPublicationsOptionsOnMobile: Locator;
  bookOfStandardsOptionsOnMobile: Locator;
  readingRoomOptionsOnMobile: Locator;
  trackerServicesOptionsOnMobile: Locator;
  catalogsOptionsOnMobile: Locator;
  specbuilderOption: Locator;
  specBuilderOptionMobile: Locator;
  ASTMCompassOption: Locator;
  ASTMCompassOptionMobile: Locator;
  integratedServicesOptions: Locator;
  integratedServicesOptionsMobile: Locator;
  digitalLibraryOptions: Locator;
  digitalLibraryOptionsOnMobile: Locator;
  enterpriseSolutionsOptions: Locator;
  customPlatforms: Locator;
  enterpriseSolutionsOptionsMobile: Locator;
  proficiencyTestingOptions: Locator;
  registerForAProgram: Locator;
  crosscookie: Locator;
  accepttermsbutton: Locator;
  confirmaddresswindow: Locator;
  useselectedaddress: Locator;
  trainingCoursesOptions: Locator;
  trainingCoursesXpathOnCart: Locator;
  memberAndOfficerTraining: Locator;
  PEContinuiningEducation: Locator;
  internationalTraning: Locator;
  allTraningCourses: Locator;
  trainingCoursesOptionsMob: Locator;
  AlltrainingCoursesOptionsMob: Locator;
  whatisASTM: Locator;
  howtogetinvolved: Locator;
  trainingandresources: Locator;
  ASTMinsightSQC: Locator;
  StandardProduct: Locator;
  certificationOptions: Locator;
  cementNConcreteReferenceLabOptions: Locator;
  ccrlOptionMobile: Locator;
  ccrlLogo: Locator;
  standardsAndPublicationsCategoriesList: Locator;
  standardsAndPublicationsCategoriesListMobile: Locator;
  enterpriseSolutionsList: Locator;
  enterpriseSolutionsListForMobile: Locator;
  trainingCoursesList: Locator;
  getInvolvedNavigation: Locator;
  newsANDeventsoption: Locator;
  getConsumerParticipation: Locator;
  meetingsAndSymposia: Locator;
  futureCommitteePDFLink: Locator;
  HeaderMeetingsSymposia: Locator;
  getMeetingsAndSymposiaLink: Locator;
  getGetInvolvedLink: Locator;
  technicalCommitteesOption: Locator;
  viewAllEvents: Locator;
  getInvolvedNavigationMobile: Locator;
  technicalCommitteesOptions: Locator;
  initiatenewstandards: Locator;
  membershipOptions: Locator;
  initiationofnewactivity: Locator;
  meetingsNSymposiaOptions: Locator;
  studentsNProfessorsOptions: Locator;
  studentsOptionsMob: Locator;
  publishWithASTMOptions: Locator;
  publishWithASTMOptionsMobile: Locator;
  membershipTypes: Locator;
  membership: Locator;
  membershipContent: Locator;
  studentsNProfessorsList: Locator;
  aboutNavigation: Locator;
  dEAndI: Locator;
  governance: Locator;
  uopStandard: Locator;
  overviewOptions: Locator;
  corporateCitizenship: Locator;
  whitePapers: Locator;
  factSheet: Locator;
  detailedOverview: Locator;
  overviewUnderOverview: Locator;
  faqsOptions: Locator;
  leadershipTeamOptions: Locator;
  governanceOptions: Locator;
  historyOptions: Locator;
  globalCooperationOptions: Locator;
  presidentColumnOptions: Locator;
  overviewList: Locator;
  governanceList: Locator;
  historyList: Locator;
  globalCooperationList: Locator;
  newsNavigation: Locator;
  standardizationNewsOptions: Locator;
  magazinesNNewslettersOptions: Locator;
  newsReleasesOptions: Locator;
  ASTMNewsOptions: Locator;
  symposiaPapersAndSTPs: Locator;
  manualsMonogramsAndData: Locator;
  memberPromoSection: Locator;
  memberPromoStatGlobalASTMStandards: Locator;
  memberPromoStatPartnerCountries: Locator;
  memberPromoStatVolunteerMembers: Locator;
  memberPromoHeader: Locator;
  memberPromoButtonLink: Locator;
  memberPromoButtonText: Locator;
  journals: Locator;
  ProficiencyTesting: Locator;
  PTPheader: Locator;
  BookOfStandarsHeader: Locator;
  ASTMStandardsTrackerHeader: Locator;
  HeaderCardTitle: Locator;
  ViewAllBtn: Locator;
  allStandardsHeader: Locator;
  SymposiaHeader: Locator;
  manualsHeader: Locator;
  STPLink: Locator;
  STPLink_5: Locator;
  STPLink_2: Locator;
  ManualLink: Locator;
  BOSPrintFormatAddToCart: Locator;
  BOSPrintFormatAddToCart_25: Locator;
  BOSOnlineFormatAddToCart: Locator;
  AddToCart: Locator;
  addToCartBtn: Locator;
  addToCartSuccessMsg: Locator;
  ProductPageTitle: Locator;
  STPTitle: Locator;
  standardTitle: Locator;
  volumeTitle: Locator;
  RegisterForAprogram: Locator;
  PTPpageHeader: Locator;
  PTPOptions: Locator;
  PTP_WeOffer: Locator;
  ProductName: Locator;
  shoppingCartLink: Locator;
  cartButton: Locator;
  ShoppingCartMessage: Locator;
  PTPprogramPage: Locator;
  PTPprice: Locator;
  RegisterProgramBtnInPTPpage: Locator;
  RegisterThisProgramBtnInPTPpage: Locator;
  PTPAlertMsg: Locator;
  journalsMob: Locator;
  ManualsMob: Locator;
  BOSImage: Locator;
  NEWSOptionsHeader: Locator;
  aboutOptionsHeader: Locator;
  getInvolvedOptionsHeader: Locator;
  compassImage: Locator;
  newsImage: Locator;
  newsDropDownImage: Locator;
  aboutImage: Locator;
  getInvolvedImage: Locator;
  allStandardsAndPublications: Locator;
  allStandardsAndPublicationsMob: Locator;
  standardsProduct: Locator;
  industrySectionOnHomepage: Locator;
  interestedInTextField: Locator;
  currentIndustrySelection: Locator;
  industrySectorDropDownButton: Locator;
  industrySectorOptions: Locator;
  industrySectorChemicalOption: Locator;
  industrySectorBuildingConstructionOption: Locator;
  industrySectorMetalsOption: Locator;
  industrySectorEnvironmentOption: Locator;
  industrySectorOilAndGasOption: Locator;
  industrySectorEnergyAndUtilitiesOption: Locator;
  industrySectorManufacturingOption: Locator;
  industrySectorAllIndustriesOption: Locator;
  footerSocialIcons: Locator;
  footerSocialIconsTwitter: Locator;
  footerSocialIconsFacebook: Locator;
  footerSocialIconsYoutube: Locator;
  footerSocialIconsLinkedln: Locator;
  footerSocialIconsInstagram: Locator;
  footerSocialIconsRSSFeed: Locator;
  catalogButton: Locator;
  customerButton: Locator;
  salesButton: Locator;
  contacts: Locator;
  addNewContact: Locator;
  createneworderButton: Locator;
  createOrder: Locator;
  contentButton: Locator;
  categoriesLink: Locator;
  productLink: Locator;
  allcustomersLink: Locator;
  ordersLink: Locator;
  addnewcustomerButton: Locator;
  pagesLink: Locator;
  ViewBtn: Locator;
  Adminsearchbykeyword: Locator;
  Adminsearchicon: Locator;
  ClearAllBtn: Locator;
  select: Locator;
  edit: Locator;
  editWithPageBuilder: Locator;
  saveSuccess_Block: Locator;
  blockLink: Locator;
  ASTMattributeCollapisible: Locator;
  AssetType: Locator;
  PublicOrderAttribute: Locator;
  astmAttributes: Locator;
  standarfamily: Locator;
  bundlewithstandard: Locator;
  inventoryitemstatuscode: Locator;
  getInvolved: Locator;
  filter: Locator;
  editLink: Locator;
  userSignin: Locator;
  PDFchild: (text: string) => Locator;
  productwithpdfversionEnabled: (text: string) => Locator;
  eventName: (eventName: string) => Locator;
  getLocationWithEventName: (eventName: string) => Locator;
  getLocation: (location: string) => Locator;
  Applyfilter: Locator;
  SKUsearch: Locator;
  CatalogPageSKU: Locator;
  title: Locator;
  urlkey: Locator;
  skuField: Locator;
  typeField: Locator;
  searchHeader: Locator;
  customerparticipation: Locator;
  whatisASTMundercustomerparticipation: Locator;
  howtogetinvolvedundercustomerparticipation: Locator;
  footerLinks: Locator;
  footerHomeLink: Locator;
  footerAboutLink: Locator;
  footerSiteMapLink: Locator;
  footerSupportLink: Locator;
  footerContactLink: Locator;
  footerPoliciesLink: Locator;
  footerPrivacyPolicyLink: Locator;
  footerAboutCopyrightPermissionsLink: Locator;
  footerReadinRoomLink: Locator;
  footerSearchbar: Locator;
  footerSearchDropdown: Locator;
  footerCopyright: Locator;
  mobileMenuNavigationExpand: Locator;
  mobileStandardsProduct: Locator;
  symposiaMob: Locator;
  mobileDigitalLibrary: Locator;
  mobileProficiencyTesting: Locator;
  mobileTrainingCourses: Locator;
  mobileCertification: Locator;
  mobileCementConcrete: Locator;
  mobileTrainingCoursesList: Locator;
  mobileBookOfStandard: Locator;
  mobileGetInvolved: Locator;
  mobileTechnicalCommittees: Locator;
  mobileMembership: Locator;
  mobileMeetingAndSymposia: Locator;
  mobilePublishwithAstm: Locator;
  mobileStudentAndProfessor: Locator;
  mobileStudentAndProfessorList: Locator;
  mobileAboutNavigationExpand: Locator;
  mobileFAQs: Locator;
  mobileLeaderShipTeam: Locator;
  mobilePresidentsColumn: Locator;
  mobileGloabalCooperation: Locator;
  mobileGlobalCooperationList: Locator;
  mobileGovernance: Locator;
  mobileGovernanceList: Locator;
  mobileHistory: Locator;
  mobileHistoryList: Locator;
  mobileOverview: Locator;
  mobileOverviewList: Locator;
  mobileNews: Locator;
  mobileStandardizationNews: Locator;
  mobileMagazinesNewsletter: Locator;
  mobileNewsReleases: Locator;
  mobileAstmInNews: Locator;
  footerSection: Locator;
  headerSection: Locator;
  breadcrumbs: Locator;
  breadcrumbsLinks: Locator;
  handleCookies: Locator;
  cookieAlert: Locator;
  OneTrustPolicyText: Locator;
  selectAnApplication: Locator;
  CompassCardTitle: Locator;
  WebStoreCardTitle: Locator;
  selectCompassBtn: Locator;
  selectWebStoreBtn: Locator;
  selectAccountInCompass: Locator;
  cookiePrivacyPolicy: Locator;
  renewMembershipLink: Locator;
  technicalLink: Locator;
  technicalCommitteeHeader: Locator;
  virtualClassroom: Locator;
  virtualClassroomHeader: Locator;
  newMemberLink: Locator;
  orderMemberPlaqueLink: Locator;
  organizationalMembershipLink: Locator;
  inviteColleagueLink: Locator;
  membershipTypesBenefits: Locator;
  membershipFAQSLink: Locator;
  contactMemberServicesLink: Locator;
  aboutASTMHeader: Locator;
  agreementLicenseText: Locator;
  responsibilitiesOfMembershipLink: Locator;
  emergingProfessionalLink: Locator;
  memberResourcesHeader: Locator;
  responsibilitiesOfASTMHeader: Locator;
  membershipLink: Locator;
  joinAdditionalCommitteeLink: Locator;
  CustomerLoginHeader: Locator;
  MembershipApplication: Locator;
  createAnAccountRenew: Locator;
  contactSalesLink: Locator;
  contactASTMHeader: Locator;
  popclose: Locator;
  digitalLibraryOverviewButton: Locator;
  ASTMLogo: Locator;
  latestText: Locator;
  cartLinkAPI: Locator;
  cartLinkAPIText: Locator;
  meetingsAndSymposiaLeftMenu: Locator;
  clickOncontinueshoppingBtn: Locator;
  metalsTestMethods: Locator;
  editSearchBoxmobile: Locator;
  goButtonMobile: Locator;
  firstTimeSearchCLoseInfo: Locator;
  gCInAbout: Locator;
  continueShoppingButton: Locator;
  activeProductsAndServicesDefault: Locator;
  activeInformationDefault: Locator;
  paginationInInfo: Locator;
  authors: Locator;
  searchInSAndP: Locator;
  ViewAll: Locator;
  STPLinkOne: Locator;
  SSMSInJournals: Locator;
  TRLinkOne: Locator;
  COVIDInLeftMenu: Locator;
  linkPersonnelCertification: Locator;
  linkEPD: Locator;
  GDPRBanner: Locator;
  GDPRRejectAll: Locator;
  GDPRAcceptAll: Locator;
  GDPRCookieSettings: Locator;
  AdditionalSettingsHeader: Locator;
  AdditionalSettingsClose: Locator;
  OneTrustCookieClose: Locator;
  CookieAlert: Locator;
  PE_ContinuingEducationLink: Locator;
  selectPlant: Locator;
  spinnerIcon: Locator;
  certificate: Locator;
  ReadOurFAQButton: Locator;
  consumerrelatedarticlesHeading: Locator;
  newsreleasesHeading: Locator;
  meetingsandeventHeading: Locator;
  howtogetinvolvedHeader: Locator;
  mediapublicityrequestform: Locator;
  trainingandresourcesHeader: Locator;
  whyshouldijoin: Locator;
  howtojoin: Locator;
  financialassistanceforcustomer: Locator;
  requestfinancialassistanceButton: Locator;
  becomeanastmmemberButton: Locator;
  newmemberorientationandtrainingButton: Locator;
  accessreadingroomButton: Locator;
  downloadtheconsumerguidebookButton: Locator;
  kathiemorganimage: Locator;
  everymemberhasavoice: Locator;
  NCATTButton: Locator;
  LMAPC: Locator;
  infographic: Locator;
  currentlyActive: Locator;
  ASTMheader: Locator;
  selectfield: Locator;
  filterpage: Locator;
  editoption: Locator;
  editpage: Locator;
  verifyhowtogetinvolved: Locator;
  EPD: Locator;
  CMSpage: Locator;
  classificationDropDown: Locator;
  customerTypeDropDown: Locator;
  SignInAdmin: Locator;
  IncomeMsgHeader: Locator;
  IncomeMsgClose: Locator;
  grandTotalInclTax: Locator;
  grandTotalIncTaxAfterSubmit: Locator;
  grandTotalExcTaxAfterSubmit: Locator;
  BookDealerDiscountOrderViewScreen: Locator;
  MemberDiscountOrderViewScreen: Locator;
  shippingAndHandlingAfterSubmit: Locator;
  totalTaxAfterSubmit: Locator;
  lineItemSubTotal: Locator;
  lineItemSubDiscount: Locator;
  lineItemTax: Locator;
  formatProductItem: Locator;
  AccountInformationTab: Locator;
  AccountInfoCustName: Locator;
  ProductTitle: Locator;
  AllTrainingsHeader: Locator;
  ProductsMenuOption: (productName: string) => Locator;
  continuebutton: Locator;
  okBtn: Locator;
  ARInvoiceType: Locator;
  ebsNumber_AccountInfoPage: Locator;
  authorizationError: Locator;
  committeLink: Locator;
  meetingsLink: Locator;
  addMeetingsequenceLink: Locator;
  addMeetingSeqMonthDropDown: Locator;
  collectionAttribute: Locator;
  meetingTypeDropDown: Locator;
  htmlCode: Locator;
  settings: Locator;
  htmlCodeInsert: Locator;
  fullScreen: Locator;
  saveBtn: Locator;
  WI_FullList_link: Locator;
  WI_FullList_linkHdr: Locator;
  cookieRejectAll: Locator;
  WI_FullList_RequiredWI: (wiNumber: string) => Locator;
  sendActivationEmailToggleInput: Locator;
  HazardousWarningText: Locator;
  useSelectedAddressBTN: Locator;
  AddmodelBoxText: Locator;
  useSelAddressTitleMagento: Locator;
  AddressEnteredRadio: Locator;
  UseSelAddText: Locator;
  confirmAddressValidation: Locator;
  wrongAddressValidation: Locator;
  useSelAddressTitle: Locator;
  ContinueBtn: Locator;
  researchReportProduct: Locator;
  addToCartButton: Locator;
  ResearchReportNames: Locator;
  SearchButton: Locator;
  committeDesginationLnks: Locator;
  addMeetingSeqcancelBtn: Locator;
  IssOrderPagechekbox: Locator;
  Enablechekbox: Locator;
  IssOrderPageDropdown: Locator;
  saveConfig: Locator;
  contactFirstName: Locator;
  contactLastName: Locator;
  contactEmail: Locator;
  TPTLearner: Locator;
  billTo: Locator;
  shipTo: Locator;
  cancelButtonOnAlert: Locator;
  selectCreditCard: Locator;
  creditcardNo: Locator;
  expirationMonth: Locator;
  expirationYear: Locator;
  cvvNumber: Locator;
  iframeccnumber: string;
  iframeExpMonth: string;
  iframeExpYear: string;
  iframecvv: string;
  headerReadingRoom: Locator;
  studentPayment: Locator;
  inResidenceTrainingPrograms: Locator;
  onlineTrainingLink: Locator;
  internationalPartnersLink: Locator;
  uaeChapterLink: Locator;
  searchptp: Locator;
  searchBtnptp: Locator;
  ptpProduct: Locator;
  ptpOil: Locator;
  contact1: Locator;
  TechnicalCommitteeFullList: Locator;
  TechnicalCommitteProduct: Locator;
  standardProduct: Locator;
  subcommitteStandard: Locator;
  searchWorkItem: Locator;
  home: Locator;
  committeAward: Locator;
  tenantMarketinghdr: Locator;
  technicalCommitteeAwards: Locator;
  otherPublisher: Locator;
  downloadCompassEbook: Locator;
  requestDemo: Locator;
  ANSIReview: Locator;
  workItem: Locator;
  lightSportAircraft: Locator;
  searchTitle: Locator;
  homeNavigation: Locator;
  standardsAndNavigation: Locator;
  standardsProductNavigation: Locator;

  constructor(page: Page) {
    this.page = page;
    this.breadcrumbsSections = page.locator("//*[@class='breadcrumbs']//ul//li");
this.journalsMouseHoverLink = page.locator("(//a[contains(text(),'Journals')])");
this.journalsLink = page.locator("(//a[contains(text(),'Journals')])[4]");
this.stpLinkInSideNav = page.locator("//a[@class='nav-link child ']/span[text()='Symposia Papers & STPs']");
this.manualsLinkInSideNav = page.locator("//a[@class='nav-link child ']/span[text()='Manuals, Monographs, & Data Series']");
this.storeLogo = page.locator("//a[@aria-label='store logo']/img");
this.MemupdatecompleteComment = page.locator("//div[text()='Membership Manual Committee Updates are complete.']");
this.ebsNumber = page.locator("//th[text()='EBS Order Number']//following-sibling::td");
this.mcsButton = page.locator("//button[contains(text(),'Go To MCS')]");
this.accountButtonStatus = page.locator("//*[@class='navbar-nav']//*[contains(@class,'fa-user-circle')]/../span");
this.languageLink = page.locator("//div[@class='astm-dropdown dropdown nav item']//*[contains(text(),'Languages')]");
this.contactLink = page.locator("text=Contact");
this.cartLink = page.locator("//span[text()='Cart']");
this.policiesLink = page.locator("text=Policies");
this.emailSubscriptionSettingsLink = page.locator("//ul//a[contains(text(),'Email Subscription')]");
this.privacyPolicyLink = page.locator("text=Privacy Policy");
// this.signInLink = page.locator("//button[@type='button'][contains(.,'SignIn')]");
this.getInvolved1 = page.locator("(//a[@id='getinvolvedDropdownMenuLink'])[1]");
this.anniversary = page.locator("(//a[text()='125th Anniversary'])[1]");
this.ConsumerParticipation = page.locator("(//a[text()='Consumer Participation'])[1]");
this.ConsumerParticipation_dropdownValues = page.locator("(//a[text()='Consumer Participation'])[1]//following-sibling::ul//li//a");
this.anniversary_dropdownValues = page.locator("(//a[text()='125th Anniversary'])[1]//following-sibling::ul//li//a");
this.dropdownValues = (value: number) => page.locator(`((//a[text()='Consumer Participation'])[1]//following-sibling::ul//li//a)[${value}]`);
this.personalcerification = page.locator("(//h4[contains(text(),'Personnel Certification')])[1]");
this.learnmoreunderpersonalcerification = page.locator("//section[@class='content-body astm-type-body--lead border-top']/a[@href='https://credentialing.training.astm.org/']");
this.SignInLink = page.locator("//div[contains(@class,'user-menu-options-dropdown')]");
this.signInLink = page.locator("//span[contains(text(),'SIGN IN') or contains(text(),'Sign In')]");
this.signInDropDown = page.locator("//div[@class='astm-dropdown dropdown user-menu-options-dropdown']//span[contains(text(),'Sign In')]");
this.signInLinkUnderDropDown = page.locator("//a[contains(text(),'Sign In')]");
this.signInButton = page.locator("(//span[contains(text(),'Sign In')])[1]");
this.createAccountButton = page.locator("//button[contains(text(),'Create Account')]");
this.continueButton = page.locator("//button[@id='save_and_continue']");
this.addContinue = page.locator("//span[text()='Continue']");
this.saveButton = page.locator("//div[@class='page-actions floating-header']/button[@id='save']");
this.AddAttributePageSaveBtn = page.locator("//button[@id='save-button']");
this.ProductPurchaseBtn = page.locator("(//button[@class=\"action tocart primary\"])[1]/span");
this.saveCustomerButton = page.locator("//div[@class='page-actions-buttons']/button[@id='save']");
this.saveCustomerBTN = page.locator("#save");
this.saveBillingReplationshipBTN = page.locator("#save:nth-child(2)");
this.saveAndContinueEdit = page.locator("//span[text()='Save and Continue Edit']");
this.checkboxdropdown = page.locator("//button[@class='action-multicheck-toggle']");
this.AddressValidationHeader = page.locator("//header[@class='modal-header']/h1[contains(text(),'Address Validation')]");
this.AddressValContinueBtn = page.locator("//button[@class='btn astm-btn btn-secondary action-accept']/span[text()='Continue']");
this.ebsOrderStatus = page.locator("span#ebs_order_status");
this.MAEOrderStatus = page.locator("span#mae_status");
// Playwright TypeScript locators
this.OrderType = page.locator("div > div.admin__page-section-item-content > table > tbody > tr:nth-child(5) > td");
this.selectAllcheckbox = page.locator("(//span[contains(text(),'Select All')])[1]");
this.addnewaddress = page.locator("//button[@class='add-new-address-button action-basic']");
this.loginLink = page.getByRole('link', { name: /Login/ });
this.myASTMLink = page.locator("//div[contains(@class,'right-navbar')]//button");
this.addproductSKU = page.locator("//span[text()='Add Products By SKU']");
this.SKUnumberTextbox = page.locator("//td[@class='col-sku']/input[@name='sku']");
this.QuantityTextbox = page.locator("//div[@class='input-box']/input[@id='sku_qty_0']");
this.contact = page.locator("//select[@id='order-billing_address_customer_contact_id']");
this.serpFirstDoc = page.locator("(//h4[contains(@class,'searchComponent_title')]/a)[1]");
this.closepopup_firsttime = page.locator("//i[@id='custom-close-overlay']");
this.addProductBtn = page.locator("//button[@id='add_products']/span");
this.addskunumber = page.locator("//td[@class=' col-sku']/input[@name='sku']");
this.addEbsSku = page.locator("//td[@class=' col-ebs_sku']/input[@name='ebs_sku']");
this.AddAnotherBtn = page.locator("//div[@class='input-box']/input[@id='sku_qty_0']/../../../td[3]//button[@title='Add another']");
this.AddToOrderBtn = page.locator("//div[@id='order-additional_area']/div/div/button[@title='Add to Order']");
this.startDate1 = page.locator("(//input[@data-datetime='start-date']/../button)[1]");
this.startDateInput = page.locator("//input[@data-datetime='start-date']");
this.publishDateInput = page.locator("//input[@data-datetime='publish-date']");
this.publishDateInput2 = page.locator("(//input[@data-datetime='publish-date'])[2]");
this.startDateInput2 = page.locator("(//input[@data-datetime='start-date'])[2]");
this.startDate2 = page.locator("(//input[@data-datetime='start-date']/../button)[2]");
this.GoToday = page.locator("//button[text()='Go Today']");
this.closebtn = page.locator("#ui-datepicker-div > div.ui-datepicker-buttonpane.ui-widget-content > button.ui-datepicker-close.ui-state-default.ui-priority-primary.ui-corner-all");
this.publishDate1 = page.locator("(//input[@data-datetime='publish-date']/../button)[1]");
this.publishDate2 = page.locator("(//input[@data-datetime='publish-date']/../button)[2]");
this.checkBox = page.locator("//input[@class='checkbox admin__control-checkbox']");
this.searchgridBtn = page.locator("(//div[@class='admin__filter-actions']/button[@class='action-default scalable action-secondary'])[2]");
this.addqty = page.locator("//input[@id='sku_qty_0']");
this.addtoOrderbutton = page.locator("//button[@data-ui-id='widget-button-10']");
this.AddressDescriptionLabel = page.locator("(//label[@class='label admin__field-label']/span[text()='Address Description'])[1]");
this.contactBillingAddress = page.locator("//select[@name='order[billing_address][customer_contact_id]']");
this.ContactBillingAddressValidation = page.locator("#order-billing_address_customer_contact_id");
this.contactShippingAddress = page.locator("//select[@name='order[shipping_address][customer_contact_id]']");
this.ContactShippingAddressValidation = page.locator("#order-shipping_address_customer_contact_id");
this.AddressInformationLabel = page.locator("//span[text()='Address Information']");
this.StreetAddressLabel = page.locator("(//span[text()='Street Address'])[1]");
this.selectContactBillingAddress = page.locator("//select[@name='order[billing_address][customer_contact_id]']/option");
this.selectContactShippingAddress = page.locator("//select[@name='order[shipping_address][customer_contact_id]']/option");
this.majorpromocode = page.locator("//select[@name='order[promo_code_major]']");
this.minorpromocode = page.locator("//select[@name='order[promo_code_minor]']");
this.orderchannel = page.locator("//select[@name='order[sales_channel]']");
this.submitorderButton = page.locator("//button[@id='submit_order_top_button']");
this.SubmitOrderBottom = page.locator("//div[@class='order-totals-actions']//button[@title='Submit Order']");
this.SubmitorderPopupOkBtn = page.locator("//button[@class='action-primary action-accept']");
this.addSelectedProduct = page.locator("//button[@title='Add Selected Product(s) to Order']");
this.eMailAddress = page.locator("//input[@name='customer[email]']");
this.CommunicationEmail = page.locator("//input[@name='customer[communication_email]']");
this.OrganizationName = page.locator("//input[@name='customer[organization_name]']");
this.searchButton = page.locator("(//button[@title='Search'])[2]");
this.publicSearchButton = page.locator("(//button[@aria-label='Search'])[2]");
this.selectsearchedcustomer = page.locator("(//tbody)[1]");
this.enterEmail = page.locator("//input[@name='email']");
this.enterCommunicationEmail = page.locator("//input[@name='communication_email']");
this.firstName = page.locator("//input[@name='customer[firstname]']");
this.lastName = page.locator("//input[@name='customer[lastname]']");
this.phoneNumber = page.locator("//input[@name='customer[phone_number]']");
this.phonenumber = page.locator("//div[@class='admin__field-control']/input[@name='telephone']");
this.zipcode = page.locator("//div[@class='admin__field-control']/input[@name='postcode']");
this.streetaddress = page.locator("//div[@class='admin__field-control']/input[@name='street[0]']");
this.country = page.locator("//div[@class='admin__field-control']/select[@name='country_id']");
this.state = page.locator("//div[@class='admin__field-control']/select[@name='region_id']");
this.city = page.locator("//div[@class='admin__field-control']/input[@name='city']");
this.onlineSubscriptions = page.locator("//a[text()='Online Subscriptions']");
this.astmLogo = page.locator("//a[@class='navbar-brand']//img");
this.TelephoneNo = page.locator("//div[@class='admin__field-control']/input[@name='customer[phone_number]']");
this.SaveCustomer = page.locator("//button[@id='save']");
this.apiLogo = page.locator("*[src*='images/logo/logo.png']");
this.searchCombobox = page.locator("(//input[contains(@placeholder,'Search topic')])[2]");
this.EnvironmentalProductDeclarations = page.locator("//div[@class='mst-search__index-title']//a[contains(text(),'Environmental Product Declarations')]");
this.searchIcon = page.locator("(//header//i[@class='fa fa-search'])[3]");
this.informationTab = page.locator("//div[@class='webm']//a[@href='https://qa.astm.org/catalogsearch/result/index/?index=8&q=%22Vinyl+Composition+Tile%22']");
this.searchASTM = page.locator("(//div[@class='mst-search__index-title']//span[contains(text(),'What is ASTM')])[1]");
this.searchhowtogetinvolved = page.locator("(//div[@class='mst-search__index-title']//span[contains(text(),'How to Get involved')])[1]");
this.searchASTMinsightSQC = page.locator("(//div[@class='mst-search__index-title']//span[contains(text(),'ASTM insight SQC')])[1]");
this.searchMarketintelligence = page.locator("(//div[@class='mst-search__index-title']//span[contains(text(),'Market Intelligence')])[1]");
this.footerSearchIcon = page.locator("//div[@class='control p-0 col-md-12 d-flex']//i[@class='fa fa-search']");
this.searchResults = page.locator(".webm li:nth-child(1) .product-item-link");
this.searchResultsCMSInfo = page.locator("//div[@class='web']//div[@class='mst-search__index mst-search__index-magento-cms-page']");
this.searchResultsPAndS = page.locator("//div[@class='webm']//ol[@class='products list items product-items']");
this.footerReadingRoom = page.locator("//div[@class='footer-content bg-primary']//a[text()='Reading Room']");
this.requestDemo1 = page.locator("(//*[@class='btn-contact btn astm-btn btn-primary mb-2'])[1]");
this.requestDemo2 = page.locator("(//*[@class='btn-contact btn astm-btn btn-primary mb-2'])[2]");
this.joinNow = page.locator("//a[contains(text(),'Join Now')]");
this.standardbycategory = page.locator("//*[contains(text(),'Browse Standards by Category')]");
this.headerSearchDropdown = page.locator("header[class*='page-header'] .header-search");
this.copydesignation = (no: number) => page.locator(`//div[@class='astm-type-body--lead']/p[${no}]`);
this.nocommitteeaffiliation = page.locator("//button[contains(text(),'No Committee Affiliation')]");
this.transportablemoisturelimitofcoal = page.locator("(//a[@href='https://qa.astm.org/ptptmlc2022.html'])[2]");
this.productsAndServices = page.locator("//a[contains(text(),'Products & Services')]");
this.productsAndServicesNavigation = page.locator("(//*[@id='productsDropdownMenuLink'])[1]");
this.StandardsAndSolutionsNew = page.locator("(//button[contains(text(),'Standards & Solutions')])[2]");
this.standardsAnsSolutionsInCartPage = page.locator("//button[contains(text(),'Standards & Solutions')]");
this.productsAndServicesNavigationMobile = page.locator("//*[@id='navbarNavDropdown']//*[@id='productsDropdownMenuLink']");
this.marketintelligence = page.locator("(//ul[@class='col-md-6 col-12']//a[contains(text(),'Market Intelligence')])[1]");
this.petrolumreferencematerial = page.locator("(//a[@href='https://qa.astm.org/products-services/petroleum-reference-materials.html'])[1]");
this.wohlersreport = page.locator("(//ul[@class='col-md-6 col-12']//a[contains(text(),'Wohlers Report')])[1]");
this.wohlerassociatelink = page.locator("//a[text()='wohlersassociates.com/2022report']");
this.marketintelligenceHeader = page.locator("//h2[contains(text(),'Market Intelligence')]");
this.wohlersreportHeader = page.locator("//h2[(text()='Wohlers Report')]");
this.petroleumreferencematerialVideo = page.locator("//div[@class='landing-header mw-730 card']");
this.petroleumreferencematerialfooterheading = page.locator("//h4[contains(text(),'Request your samples and start improving your processes and equipment today.')]");
this.petroleumreferencematerialfootercontactUs = page.locator("//h4[@class='astm-type-heading--h4 mb-3 pt-2']/following::a[@href='mailto:refmat@astm.org']");
this.unlimitedaccessnowavailable = page.locator("//h5[(text()='Unlimited Access Now Available')]");
this.learnmoreaboutASTMrefmats = page.locator("//a[@href='http://astmrefmat.training.astm.org/#/']");
this.marketintelligenceotherheadings = page.locator("//div[@class='border-bottom pb-3 mb-3']");
this.contactUsundermarketintelligence = page.locator("//div[@class='mb-2 pt-2']//a[@class='btn-contact btn astm-btn btn-primary mb-2']");
this.contactUsunderwohlerreport = page.locator("//div[@class='border-bottom mb-3']//a[@class='btn-contact btn astm-btn btn-primary mb-4']");
this.learnmoreaboutwohlersbutton = page.locator("//*[contains(text(),'Learn more about Wohlers')]");
this.learnmoreaboutwohlersimage = page.locator("//img[@class='mb-3']");
this.membershipHeader = page.locator("//h4[text()='Membership']");
this.participatingHeader = page.locator("//h1[text()='Thank you for your interest in membership.']");
this.standardsAndPublicationsOptions = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Standards & Publications')]");
this.standardsAndSolutions = page.locator("//button[contains(text(),'Standards & Solutions')]");
this.signOutMenu = page.locator("//span[@data-testid='usernameBtn']");
this.signOutLink = page.locator("//button[text()='Sign Out']");
this.LaboratoryServicesOptions = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Laboratory Services')]");
this.BookfStandardsOptions = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Book of Standards')]");
this.fontenotmaillink = page.locator("//a[@href='mailto:afontenot@astm.org']");
this.phoneNoUnderdvisoryservices = page.locator("//div[@class='mb-2 pt-2']/span[contains(text(),'877-909-2786')]");
this.phoneNoUndercontactustodayforallyourAMconsultingneeds = page.locator("//div[@class='mb-1']/span[contains(text(),'877-909-2786')]");
this.ptpmailLink = page.locator("//a[@href='mailto:ptp@astm.org']");
this.PTPShippingPolicy = page.locator("//*[text()='ASTM PTP Shipping Policy:']");
this.fontenotphonenumber = page.locator("//a[@href='tel:+16108329748']");
this.standardsProducts = page.locator("(//a[@class='dropdown-item'][contains(text(),'Standards Products')])[1]");
this.technicalReports = page.locator("//nav[contains(@class,'astm-navbar')]//a[text()='Technical Reports']");
this.wohlerimage = page.locator("//img[@src='https://qa.astm.org/media/wysiwyg/wohlers-report.png']");
this.bookOfStandardsOptions = page.locator("//nav[contains(@class,'astm-navbar')]//li[@class='dropdown-submenu']/preceding-sibling::li/a[contains(text(),'Book of Standards')]");
this.annualBookOfStandards = page.locator("//a[contains(text(), 'Annual Book of Standards')]");
this.readingRoomOptions = page.locator("//nav[contains(@class,'astm-navbar')]//li[@class='dropdown-submenu']/preceding-sibling::li/a[contains(text(),'Reading Room')]");
this.readingRoomInSAndP = page.locator("//nav[contains(@class,'astm-navbar')]//ul[@class='dropdown-menu show']//a[text()='Reading Room']");
this.trackerServicesOptions = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Tracker Services')]");
this.catalogsOptions = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Catalogs')]");
this.standardsAndPublicationsOptionsOnMobile = page.locator("//nav[contains(@class,'main-nav-mobile')]//a[contains(text(),'Standards & Publications')]");
this.bookOfStandardsOptionsOnMobile = page.locator("//nav[contains(@class,'main-nav-mobile')]//li[@class='dropdown-submenu']/preceding-sibling::li/a[contains(text(),'Book of Standards')]");
this.readingRoomOptionsOnMobile = page.locator("//nav[contains(@class,'main-nav-mobile')]//li[@class='dropdown-submenu']/preceding-sibling::li/a[contains(text(),'Reading Room')]");
this.trackerServicesOptionsOnMobile = page.locator("//nav[contains(@class,'main-nav-mobile')]//a[contains(text(),'Tracker Services')]");
this.catalogsOptionsOnMobile = page.locator("//nav[contains(@class,'main-nav-mobile')]//a[contains(text(),'Catalogs')]");
this.specbuilderOption = page.locator("//nav[contains(@class,'astm-navbar')]//*[text()='SpecBuilder']");
this.specBuilderOptionMobile = page.locator("//nav[contains(@class,'main-nav-mobile')]//*[text()='SpecBuilder']");
this.ASTMCompassOption = page.locator("//nav[contains(@class,'astm-navbar')]//*[contains(text(),'ASTM Compass')]");
this.ASTMCompassOptionMobile = page.locator("//nav[contains(@class,'main-nav-mobile')]//*[text()='ASTM Compass�']");
this.integratedServicesOptions = page.locator("//nav[contains(@class,'astm-navbar')]//*[text()='Integrated Services']");
this.integratedServicesOptionsMobile = page.locator("//nav[contains(@class,'main-nav-mobile')]//*[text()='Integrated Services']");
this.digitalLibraryOptions = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Digital Library')]");
this.digitalLibraryOptionsOnMobile = page.locator("//nav[contains(@class,'main-nav-mobile')]//a[contains(text(),'Digital Library')]");
this.enterpriseSolutionsOptions = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Enterprise Solutions')]");
this.customPlatforms = page.locator("//nav[contains(@class,'astm-navbar')]//a[text()='Custom Platforms']");
this.enterpriseSolutionsOptionsMobile = page.locator("//nav[contains(@class,'main-nav-mobile')]//a[contains(text(),'Enterprise Solutions')]");
this.proficiencyTestingOptions = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Proficiency Testing')]");
this.registerForAProgram = page.locator("//a[contains(text(),'Register for a Program')]");
this.crosscookie = page.locator(".onetrust-close-btn-handler.onetrust-close-btn-ui.banner-close-button.ot-close-icon");
this.accepttermsbutton = page.locator("//div[@class='actions mt-4 d-flex']/a[@href='https://qa.astm.org/customer/account/create/']");
this.confirmaddresswindow = page.locator("//h1[@id='modal-title-16']");
this.useselectedaddress = page.locator("//button[@class='btn astm-btn btn-secondary action-accept']");
this.trainingCoursesOptions = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Training Courses ')]");
this.trainingCoursesXpathOnCart = page.locator("//div[@class='nestedMenuContainer']//a[contains(text(), 'Training Courses')]");
this.memberAndOfficerTraining = page.locator("//nav[contains(@class,'astm-navbar')]//*[text()='Member and Officer Training']");
this.PEContinuiningEducation = page.locator("//nav[contains(@class,'astm-navbar')]//*[text()='PE Continuing Education']");
this.internationalTraning = page.locator("//nav[contains(@class,'astm-navbar')]//*[text()='International Training']");
this.allTraningCourses = page.locator("//nav[contains(@class,'astm-navbar')]//*[contains(text(),'All Training')]");
this.trainingCoursesOptionsMob = page.locator("//nav[contains(@class,'main-nav-mobil')]//a[contains(text(),'Training Courses ')]");
this.AlltrainingCoursesOptionsMob = page.locator("//nav[contains(@class,'main-nav-mobile')]//a[contains(text(),'All Training Courses')]");
this.whatisASTM = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'What is ASTM')]");
this.howtogetinvolved = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'How to Get Involved')]");
this.trainingandresources = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Training and Resources')]");
this.ASTMinsightSQC = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'ASTM Insight SQC')]");
this.StandardProduct = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Standards Products')]");
this.certificationOptions = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Certification')]");
this.cementNConcreteReferenceLabOptions = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Cement & Concrete Reference Lab')]");
this.ccrlOptionMobile = page.locator("//*[@id='navbarNavDropdown']//a[@class='dropdown-item' and contains(text(),'Cement & Concrete Reference Lab')]");
this.ccrlLogo = page.locator("//*[@src='Images/ASTM_Logo_White.png']");
this.standardsAndPublicationsCategoriesList = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Standards & Publications')]/..//li/a");
this.standardsAndPublicationsCategoriesListMobile = page.locator("//nav[contains(@class,'main-nav-mobile')]//a[contains(text(),'Standards & Publications')]/following-sibling::ul//li//a");
this.enterpriseSolutionsList = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Enterprise Solutions')]/..//li/a");
this.enterpriseSolutionsListForMobile = page.locator("//nav[contains(@class,'main-nav-mobile')]//a[contains(text(),'Enterprise Solutions')]/..//li/a");
this.trainingCoursesList = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Training Courses ')]/..//li/a");
this.getInvolvedNavigation = page.locator("(//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Get Involved')])[1]");
this.newsANDeventsoption = page.locator("//a[@class='nav-link child ']//span[text()='News and Events']");
this.getConsumerParticipation = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Consumer Participation')]");
this.meetingsAndSymposia = page.locator("//div[@class='dropdown-menu nav-submenu-with-bg m-0 row get-involved show']//a[text()='Meetings & Symposia']");
this.futureCommitteePDFLink = page.locator("//a[contains(text(),'Future Committee Week Locations (PDF)')]");
this.HeaderMeetingsSymposia = page.locator("//h1");
this.getMeetingsAndSymposiaLink = page.locator("//a[text()='Meetings & Symposia']");
this.getGetInvolvedLink = page.locator("//a[text()='Get Involved']");
this.technicalCommitteesOption = page.locator("//a[contains(text(),'Technical Committees')]");
this.viewAllEvents = page.locator("//a[text()='View All Events']");
this.getInvolvedNavigationMobile = page.locator("(//*[@id='navbarDropdownMenuLink'])[6]");
this.technicalCommitteesOptions = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Technical Committees')]");
this.initiatenewstandards = page.locator("//*[@href='/get-involved/technical-committees/new-standards-development.html']");
this.membershipOptions = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Membership')]");
this.initiationofnewactivity = page.locator("//*[contains(text(),'Initiation of New Activity')]");
this.meetingsNSymposiaOptions = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Meetings & Symposia')]");
this.studentsNProfessorsOptions = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Students & Professors')]");
this.studentsOptionsMob = page.locator("//nav[contains(@class,'main-nav-mobile')]//a[contains(text(),'For Students')]");
this.publishWithASTMOptions = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Publish With ASTM')]");
this.publishWithASTMOptionsMobile = page.locator("//nav[contains(@class,'main-nav-mobile')]//a[contains(text(),'Publish With ASTM')]");
this.membershipTypes = page.locator("//span[contains(text(),'Membership Types')]");
this.membership = page.locator("//h1[text()='Membership']");
this.membershipContent = page.locator("//p[contains(text(),'Membership with ASTM')]");
this.studentsNProfessorsList = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Students & Professors ')]/..//li/a");
this.aboutNavigation = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'About')]");
this.dEAndI = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(), 'Diversity, Equity, & Inclusion')]");
this.governance = page.locator("//nav[contains(@class,'astm-navbar')]//a[text()='Governance']");
this.uopStandard = page.locator("//a[text()='UOP Standards']");
this.overviewOptions = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Overview ')]");
this.corporateCitizenship = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Corporate')]");
this.whitePapers = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'White Papers')]");
this.factSheet = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Fact Sheet')]");
this.detailedOverview = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Detailed Overview')]");
this.overviewUnderOverview = page.locator("//nav[contains(@class,'astm-navbar')]//a[text()='Overview']");
this.faqsOptions = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'FAQs')]");
this.leadershipTeamOptions = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Leadership Team')]");
this.governanceOptions = page.locator("(//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Governance')])[1]");
this.historyOptions = page.locator("(//nav[contains(@class,'astm-navbar')]//a[contains(text(),'History ')])[1]");
this.globalCooperationOptions = page.locator("//a[text()='Global Cooperation ']");
this.presidentColumnOptions = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'s Column')]");
this.overviewList = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Overview ')]/..//li/a");
this.governanceList = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Governance')]/..//li/a");
this.historyList = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'History ')]/..//li/a");
this.globalCooperationList = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Global Cooperation ' )]/..//li/a");
this.newsNavigation = page.locator("//nav[contains(@class,'astm-navbar')]//a[@id='newsDropdownMenuLink' and contains(text(),'News')]");
this.standardizationNewsOptions = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Standardization News')]");
this.magazinesNNewslettersOptions = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'Magazines & Newsletters')]");
this.newsReleasesOptions = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'News Releases')]");
this.ASTMNewsOptions = page.locator("//nav[contains(@class,'astm-navbar')]//a[contains(text(),'ASTM in the News')]");
this.symposiaPapersAndSTPs = page.locator("//nav[contains(@class,'astm-navbar')]//a[text()='Symposia Papers & STPs']");
this.manualsMonogramsAndData = page.locator("//nav[contains(@class,'astm-navbar')]//a[text()='Manuals, Monographs, & Data Series']");

this.memberPromoSection = page.locator("//*[@id='info-membership']");
this.memberPromoStatGlobalASTMStandards = page.locator("//*[@id='info-membership']//*[@class='row']//span[contains(@class, 'stat-title') and contains(text(), 'Global ASTM Standards')]/preceding-sibling::span[@class='stat-number']");
this.memberPromoStatPartnerCountries = page.locator("//*[@id='info-membership']//*[@class='row']//span[contains(@class, 'stat-title') and contains(text(), 'Partner Countries')]/preceding-sibling::span[@class='stat-number']");
this.memberPromoStatVolunteerMembers = page.locator("//*[@id='info-membership']//*[@class='row']//span[contains(@class, 'stat-title') and contains(text(), 'Volunteer Members')]/preceding-sibling::span[@class='stat-number']");
this.memberPromoHeader = page.locator("//*[@id='info-membership']//*[@class='astm-type-heading--h2']");
this.memberPromoButtonLink = page.locator("//*[@id='info-membership']//*[@class='row']//a");
this.memberPromoButtonText = page.locator("//*[@id='info-membership']//*[@class='row']//a//button");

this.journals = page.locator("(//a[contains(@href,'journals')])[1]");
this.ProficiencyTesting = page.locator("//nav[contains(@class,'astm-navbar')]//a[text()='Proficiency Testing']");
this.PTPheader = page.locator("//h2[contains(text(),'Proficiency Testing')]");
this.BookOfStandarsHeader = page.locator("//h2[text()='Annual Book of ASTM Standards']");
this.ASTMStandardsTrackerHeader = page.locator("//h2[contains(text(),'ASTM Standards Tracker')]");
this.HeaderCardTitle = page.locator("//h2[contains(@class,'title')]");
this.ViewAllBtn = page.locator("//h4[@class='card-header astm-type-heading--h4']/a");
this.allStandardsHeader = page.locator("//h2[contains(@class,'title')]");
this.SymposiaHeader = page.locator("//div[contains(@class,'wysiwygContainer')]/h2");
this.manualsHeader = page.locator("//div[contains(@class,'wysiwygContainer')]/h2");
this.STPLink = page.locator("//div[contains(@class,'wysiwygContainer')]/p[1]/a");
this.STPLink_5 = page.locator("//div[contains(@class,'wysiwygContainer')]/p[5]/a");
this.STPLink_2 = page.locator("//div[contains(@class,'wysiwygContainer')]/p[2]/a");

this.ManualLink = page.locator("//div[@class='all-container']/h1/../../div[2]/p[1]/a");
this.BOSPrintFormatAddToCart = page.locator("(//form[contains(@id,'product_addtocart_form')])[last()]");
this.BOSPrintFormatAddToCart_25 = page.locator("//button[@title='Add to Cart']");
this.BOSOnlineFormatAddToCart = page.locator("#product_addtocart_form_4141216 > button");
this.AddToCart = page.locator("//button[@title='Add to Cart']");
this.addToCartBtn = page.locator("//button[@title='Add to Cart' and contains(@class,'astm-btn')]");
this.addToCartSuccessMsg = page.locator("//div[@class='prepare-message astm-alert-text']");
this.ProductPageTitle = page.locator("//span[@class='base']");
this.STPTitle = page.locator("//h3[@class='astm-type-heading--h3']/b");
this.standardTitle = page.locator("//h1[contains(@class,'astm-type-heading--h3')]/b");
this.volumeTitle = page.locator("//div[1]/h2/span");
this.RegisterForAprogram = page.locator("//a[text()='Register for a Program']");
this.PTPpageHeader = page.locator("//span[text()='Register For Multiple PTP Programs']");
this.PTPOptions = page.locator("//h4[text()='Proficiency Testing Program Options']");
this.PTP_WeOffer = page.locator("//p[contains(text(),'We offer')]");
this.ProductName = page.locator("//h3[@class='astm-type-heading--h3']/b");
this.shoppingCartLink = page.locator("text=shopping cart");
this.cartButton = page.locator("//span[text()='Cart']");
this.ShoppingCartMessage = page.locator("//div[@class='prepare-message astm-alert-text']");
this.PTPprogramPage = page.locator("//h1/span");
this.PTPprice = page.locator("//span[@class='price']");
this.RegisterProgramBtnInPTPpage = page.locator("//button[@title='Register for this Program']");
this.RegisterThisProgramBtnInPTPpage = page.locator("//button[@title='Register for this Program']");
this.PTPAlertMsg = page.locator("//div[contains(@class,'alert-text')]");

this.journalsMob = page.locator("//nav[contains(@class,'main-nav-mobile')]//a[contains(text(),'Journals')]");
this.ManualsMob = page.locator("//nav[contains(@class,'main-nav-mobile')]//a[contains(text(),'Manuals, Monographs, & Data Series')]");
this.BOSImage = page.locator("//nav[contains(@class,'astm-navbar')]//img[contains(@src,'bookstore.jpg')]");
this.NEWSOptionsHeader = page.locator("//nav[contains(@class,'astm-navbar')]//span[text()='NEWS']");
this.aboutOptionsHeader = page.locator("//nav[contains(@class,'astm-navbar')]//span[text()='OVERVIEW & KEY FACTS']");
this.getInvolvedOptionsHeader = page.locator("//nav[contains(@class,'astm-navbar')]//span[text()='MEMBERSHIP & MEETINGS']");
this.compassImage = page.locator("//nav[contains(@class,'astm-navbar')]//img[contains(@src,'compass-new-logo')]");
this.newsImage = page.locator("//nav[contains(@class,'astm-navbar')]//img[contains(@src,'MA21-SN-Cover-sm.jpg')]");
this.newsDropDownImage = page.locator("//nav[contains(@class,'astm-navbar')]//div[@aria-labelledby='newsDropdownMenuLink']//img");
this.aboutImage = page.locator("//nav[contains(@class,'astm-navbar')]//img[contains(@src,'about-nav')]");
this.getInvolvedImage = page.locator("//nav[contains(@class,'astm-navbar')]//img[contains(@src,'get-involved-nav')]");
this.allStandardsAndPublications = page.locator("(//a[@class='dropdown-item'][contains(text(),'All Standards and Publications')])[1]");
this.allStandardsAndPublicationsMob = page.locator("//nav[contains(@class,'main-nav-mobile')]//*[contains(text(),'All Standards and Publications')]");
this.standardsProduct = page.locator("(//a[@class='dropdown-item'][contains(text(),'Standards Products')])[1]");

this.industrySectionOnHomepage = page.locator("//*[@class='home-choose-industry bg-primary']");
this.interestedInTextField = page.locator("//*[@class='home-choose-industry bg-primary']//div[@class='row']/h4");
this.currentIndustrySelection = page.locator("//*[@class='home-choose-industry bg-primary']//div[@class='row']//*[@class='industry-link']/a");
this.industrySectorDropDownButton = page.locator("//*[@class='home-choose-industry bg-primary']//*[@class='astm-dropdown dropdown']//button");
this.industrySectorOptions = page.locator("//*[@class='home-choose-industry bg-primary']//*[@class='dropdown-menu show']/a");

this.industrySectorChemicalOption = page.locator("//*[@class='home-choose-industry bg-primary']//*[@class='dropdown-menu show']/a[contains(text(), 'Chemicals')]");
this.industrySectorBuildingConstructionOption = page.locator("//*[@class='home-choose-industry bg-primary']//*[@class='dropdown-menu show']/a[contains(text(), 'Building Construction')]");
this.industrySectorMetalsOption = page.locator("//*[@class='home-choose-industry bg-primary']//*[@class='dropdown-menu show']/a[contains(text(), 'Metals')]");
this.industrySectorEnvironmentOption = page.locator("//*[@class='home-choose-industry bg-primary']//*[@class='dropdown-menu show']/a[contains(text(), 'Environment')]");
this.industrySectorOilAndGasOption = page.locator("//*[@class='home-choose-industry bg-primary']//*[@class='dropdown-menu show']/a[contains(text(), 'Oil & Gas')]");
this.industrySectorEnergyAndUtilitiesOption = page.locator("//*[@class='home-choose-industry bg-primary']//*[@class='dropdown-menu show']/a[contains(text(), 'Energy & Utilities')]");
this.industrySectorManufacturingOption = page.locator("//*[@class='home-choose-industry bg-primary']//*[@class='dropdown-menu show']/a[contains(text(), 'Manufacturing')]");
this.industrySectorAllIndustriesOption = page.locator("//*[@class='home-choose-industry bg-primary']//*[@class='dropdown-menu show']/a[contains(text(), 'All Industries')]");

this.footerSocialIcons = page.locator("//*[@class='footer-social-icons']//a");
this.footerSocialIconsTwitter = page.locator("//*[@class='footer-social-icons']//*[contains(@class, 'fab fa-twitter-square')]");
this.footerSocialIconsFacebook = page.locator("//*[@class='footer-social-icons']//*[contains(@class, 'fab fa-facebook-square')]");
this.footerSocialIconsYoutube = page.locator("//*[@class='footer-social-icons']//*[contains(@class, 'fab fa-youtube-square')]");
this.footerSocialIconsLinkedln = page.locator("//*[@class='footer-social-icons']//*[contains(@class, 'fab fa-youtube-square')]");
this.footerSocialIconsInstagram = page.locator("//*[@class='footer-social-icons']//*[contains(@class, 'fab fa-instagram-square')]");
this.footerSocialIconsRSSFeed = page.locator("//*[@class='footer-social-icons']//*[contains(@class, 'fas fa-rss-square')]");
this.catalogButton = page.locator("//*[@id='menu-magento-catalog-catalog']");
this.customerButton = page.locator("//*[@id='menu-magento-customer-customer']");
this.salesButton = page.locator("//*[@id='menu-magento-sales-sales']");
this.contacts = page.locator("//span[text()='Contacts']");
this.addNewContact = page.locator("//span[text()='Add New Contact']");
this.createneworderButton = page.locator("//button[@title='Create New Order']");
this.createOrder = page.locator("//button[@id='order']");
this.contentButton = page.locator("//*[@id='menu-magento-backend-content']");
this.categoriesLink = page.locator("text=Categories");
this.productLink = page.locator("text=Products");
this.allcustomersLink = page.locator("text=All Customers");
this.ordersLink = page.locator("text=Orders");
this.addnewcustomerButton = page.locator("//button[@id='add']");
this.pagesLink = page.locator("text=Pages");
this.ViewBtn = page.locator("//a[text()='View']");
this.Adminsearchbykeyword = page.locator("(//input[@class='admin__control-text data-grid-search-control'])[1]");
this.Adminsearchicon = page.locator("(//input[@class='admin__control-text data-grid-search-control']/following::button[@class='action-submit'])[1]");
this.ClearAllBtn = page.locator("(//button[text()='Clear all'])[1]");
this.select = page.locator("//button[text()='Select']");
this.edit = page.locator("//a[text()='Edit']");
this.editWithPageBuilder = page.locator("//span[text()='Edit with Page Builder']");
this.saveSuccess_Block = page.locator("//div[text()='You saved the block.']");
this.blockLink = page.locator("text=Blocks");
this.ASTMattributeCollapisible = page.locator("#container > div > div.entry-edit.form-inline > div:nth-child(7) > div.fieldset-wrapper-title");
this.AssetType = page.locator("//span[text()='Asset Type']");
this.PublicOrderAttribute = page.locator("//input[@name='product[disable_public_order]']");
this.astmAttributes = page.locator("//div[@class='fieldset-wrapper-title']//span[text()='ASTM Attributes']");
this.standarfamily = page.locator("//input[@name='product[standard_family]']");
this.bundlewithstandard = page.locator("//input[@name='product[bundle_with_standard]'][@value='1']");
this.inventoryitemstatuscode = page.locator("//input[@name='product[inventory_item_status_code]']");
this.getInvolved = page.locator("#ext-gen34");
this.filter = page.locator("(//div[@class='data-grid-filters-action-wrap'])[1]");
this.editLink = page.locator("//a[@class='action-menu-item'][contains(text(),'Edit')]");
this.userSignin = page.locator("//span[text()='testuser']");
this.PDFchild = (text: string) => page.locator(`//tr/td//*[text()='${text}-PDF']/../preceding::td//following-sibling::div[@class='admin__field-control']//a`);
this.productwithpdfversionEnabled = (text: string) => page.locator(`//tr/td//*[text()='${text}-PDF']/../following::td/div`);
this.eventName = (eventName: string) => page.locator(`(//p[text()='${eventName}'])[1]`);
this.getLocationWithEventName = (eventName: string) => page.locator(`(//p[text()='${eventName}'])[1]/..//p[3]`);
this.getLocation = (location: string) => page.locator(`(//p[text()='${location}'])[1]`);
this.Applyfilter = page.locator(".action-secondary");
this.SKUsearch = page.locator("tbody > tr > td:nth-child(7) > div");
this.CatalogPageSKU = page.locator("//input[@name='product[sku]']");
this.title = page.locator("//div[@class='admin__form-field-control']//input[@name='title']");
this.urlkey = page.locator("//div[@class='admin__form-field-control']//input[@name='identifier']");
this.skuField = page.locator("//div[@class='admin__form-field-control']//input[@name='sku']");
this.typeField = page.locator("//div[@class='admin__form-field-control']//select[@name='type_id']");
this.searchHeader = page.locator("(//*[@class='input-text form-control pr-1'])[1]");
this.customerparticipation = page.locator("//img[@class='x-tree-ec-icon x-tree-elbow-end-plus']");
this.whatisASTMundercustomerparticipation = page.locator("#extdd-25");
this.howtogetinvolvedundercustomerparticipation = page.locator("#extdd-37");
this.footerLinks = page.locator("//*[@class='footer-content bg-primary']//*[@class='nav-item']//a");
this.footerHomeLink = page.locator("//*[@class='footer-content bg-primary']//*[@class='navbar-nav']//a[contains(text(), 'Home')]");
this.footerAboutLink = page.locator("//*[@class='footer-content bg-primary']//*[@class='navbar-nav']//a[contains(text(), 'About')]");
this.footerSiteMapLink = page.locator("//*[@class='footer-content bg-primary']//*[@class='navbar-nav']//a[contains(text(), 'Site Map')]");
this.footerSupportLink = page.locator("//*[@class='footer-content bg-primary']//*[@class='navbar-nav']//a[contains(text(), 'Support')]");
this.footerContactLink = page.locator("//*[@class='footer-content bg-primary']//*[@class='navbar-nav']//a[contains(text(), 'Contact')]");
this.footerPoliciesLink = page.locator("//*[@class='footer-content bg-primary']//*[@class='nav-item']//a[contains(text(), 'Policies')]");
this.footerPrivacyPolicyLink = page.locator("//*[@class='footer-content bg-primary']//*[@class='navbar-nav']//a[contains(text(), 'Privacy Policy')]");
this.footerAboutCopyrightPermissionsLink = page.locator("//*[@class='footer-content bg-primary']//*[@class='navbar-nav']//a[contains(text(), 'Copyright/Permissions')]");
this.footerReadinRoomLink = page.locator("//*[@class='footer-content bg-primary']//*[@class='navbar-nav']//a[contains(text(), 'Reading Room')]");
this.footerSearchbar = page.locator("//*[@class='footer-content bg-primary']//*[@id='search-footer']");
this.footerSearchDropdown = page.locator("//*[@id='search_mini_form_footer']//select");
this.footerCopyright = page.locator("//*[@class='footer-content bg-primary']//*[@class='copyright']//span");

this.mobileMenuNavigationExpand = page.locator(".navbar-toggler-btn");

this.mobileStandardsProduct = page.locator("//nav[contains(@class,'main-nav-mobile')]//a[contains(text(),'Standards Products')]");
this.symposiaMob = page.locator("//nav[contains(@class,'main-nav-mobile')]//a[contains(text(),'Symposia Papers & STPs')]");
this.mobileDigitalLibrary = page.locator("//nav[contains(@class,'main-nav-mobile')]//a[contains(text(),'Digital Library')]");
this.mobileProficiencyTesting = page.locator("//nav[contains(@class,'main-nav-mobile')]//a[text()='Proficiency Testing']");
this.mobileTrainingCourses = page.locator("//nav[contains(@class,'main-nav-mobile')]//a[text()='Training Courses ']");
this.mobileCertification = page.locator("//nav[contains(@class,'main-nav-mobile')]//a[text()='Certification']");
this.mobileCementConcrete = page.locator("//nav[contains(@class,'main-nav-mobile')]//a[text()='Cement & Concrete Reference Lab']");
this.mobileTrainingCoursesList = page.locator("//nav[contains(@class,'nav-mobile')]//a[contains(text(),'Training ' )]/..//li/a");
this.mobileBookOfStandard = page.locator("//nav[contains(@class,'main-nav-mobile')]//a[text()='Book of Standards']");

this.mobileGetInvolved = page.locator("(//*[@id='navbarDropdownMenuLink'])[6]");
this.mobileTechnicalCommittees = page.locator("//nav[contains(@class,'nav-mobile')]//a[(text()='Technical Committees')]");
this.mobileMembership = page.locator("//nav[contains(@class,'nav-mobile')]//a[(text()='Membership')]");
this.mobileMeetingAndSymposia = page.locator("//nav[contains(@class,'nav-mobile')]//a[(text()='Meetings & Symposia')]");
this.mobilePublishwithAstm = page.locator("//nav[contains(@class,'nav-mobile')]//a[(text()='Publish With ASTM')]");
this.mobileStudentAndProfessor = page.locator("//nav[contains(@class,'nav-mobile')]//a[text()='Students & Professors ']");
this.mobileStudentAndProfessorList = page.locator("//nav[contains(@class,'nav-mobile')]//a[text()='Students & Professors ']/..//li/a");

this.mobileAboutNavigationExpand = page.locator("//nav[contains(@class,'nav-mobile')]//a[contains(text(),'About')]");
this.mobileFAQs = page.locator("//nav[contains(@class,'nav-mobile')]//a[(text()='FAQs')]");
this.mobileLeaderShipTeam = page.locator("//nav[contains(@class,'nav-mobile')]//a[(text()='Leadership Team')]");
this.mobilePresidentsColumn = page.locator("//nav[contains(@class,'nav-mobile')]//a[(text()=\"President's Column\")]");
this.mobileGloabalCooperation = page.locator("//nav[contains(@class,'nav-mobile')]//a[(text()='Global Cooperation ')]");
this.mobileGlobalCooperationList = page.locator("//nav[contains(@class,'nav-mobile')]//a[contains(text(),'Global Cooperation ' )]/..//li/a");
this.mobileGovernance = page.locator("//nav[contains(@class,'nav-mobile')]//a[text()='Governance ']");
this.mobileGovernanceList = page.locator("//nav[contains(@class,'nav-mobile')]//a[contains(text(),'Governance ' )]/..//li/a");
this.mobileHistory = page.locator("//nav[contains(@class,'nav-mobile')]//a[text()='History ']");
this.mobileHistoryList = page.locator("//nav[contains(@class,'nav-mobile')]//a[contains(text(),'History ' )]/..//li/a");
this.mobileOverview = page.locator("//nav[contains(@class,'nav-mobile')]//a[text()='Overview ']");
this.mobileOverviewList = page.locator("//nav[contains(@class,'nav-mobile')]//a[text()='Overview ']/..//li/a");

this.mobileNews = page.locator("(//*[@id='navbarDropdownMenuLink'])[8]");
this.mobileStandardizationNews = page.locator("//nav[contains(@class,'nav-mobile')]//a[(text()='Standardization News')]");
this.mobileMagazinesNewsletter = page.locator("//nav[contains(@class,'nav-mobile')]//a[(text()='Magazines & Newsletters')]");
this.mobileNewsReleases = page.locator("//nav[contains(@class,'nav-mobile')]//a[(text()='News Releases')]");
this.mobileAstmInNews = page.locator("//nav[contains(@class,'nav-mobile')]//a[(text()='ASTM in the News')]");
this.footerSection = page.locator("*[class*='footer-content']");
this.headerSection = page.locator("*[class='page-header m-0 astm-header']");
this.breadcrumbs = page.locator("*[class='breadcrumb astm-breadcrumb']");
this.breadcrumbsLinks = page.locator("//*[@class='breadcrumbs']//ul//a");
this.handleCookies = page.locator("#btn-cookie-allow");
this.cookieAlert = page.locator(".astm-alert-text");
this.OneTrustPolicyText = page.locator("#onetrust-policy-text");
this.selectAnApplication = page.locator("//h3[text()='Select an Application']");
this.CompassCardTitle = page.locator("//h3[contains(@class,'card-title mb-0')]/span[text()='Compass']");
this.WebStoreCardTitle = page.locator("//h3[contains(@class,'card-title mb-0')]/span[text()='Web Store']");
this.selectCompassBtn = page.locator("//h3[contains(@class,'card-title mb-0')]/span[text()='Compass']/../../button");
this.selectWebStoreBtn = page.locator("//h3[contains(@class,'card-title mb-0')]/span[text()='Web Store']/../../button");
this.selectAccountInCompass = page.locator("//h1[text()='Select an Account']/../p[2]/button");
this.cookiePrivacyPolicy = page.locator("text=privacy policy");
this.renewMembershipLink = page.locator("//a[contains(text(),'Renew')]");
this.technicalLink = page.locator("//a[contains(text(),'Technical Committees & Resources')]");
this.technicalCommitteeHeader = page.locator("//h1[text()='Technical Committees']");
this.virtualClassroom = page.locator("//a[contains(text(),'Virtual Classroom')]");
this.virtualClassroomHeader = page.locator("//h1[text()='Classroom for Members']");
this.newMemberLink = page.locator("//a[contains(text(),'New Member')]");
this.orderMemberPlaqueLink = page.locator("//a[contains(text(),'Order a')]");
this.organizationalMembershipLink = page.locator("//a[contains(text(),'Organizational Member')]");
this.inviteColleagueLink = page.locator("//a[contains(text(),'Invite')]");
this.membershipTypesBenefits = page.locator("//a[contains(text(),'Membership Types')]");
this.membershipFAQSLink = page.locator("//a[contains(text(),'Membership F')]");
this.contactMemberServicesLink = page.locator("//a[contains(text(),'Contact Member')]");
this.aboutASTMHeader = page.locator("//h1[text()='About ASTM Membership']");
this.agreementLicenseText = page.locator("//*[@class='table data section contents']");
this.responsibilitiesOfMembershipLink = page.locator("//a[contains(text(),'Responsibilities of')]");
this.emergingProfessionalLink = page.locator("//a[contains(text(),'Emerging')]");
this.memberResourcesHeader = page.locator("//h1[text()='Member Resources']");
this.responsibilitiesOfASTMHeader = page.locator("//h1[contains(text(),'Responsibilities')]");
this.membershipLink = page.locator("//span[text()='Membership']");
this.joinAdditionalCommitteeLink = page.locator("//a[contains(text(),'Join Additional Committee')]");
this.CustomerLoginHeader = page.locator("//span[text()='Customer Login']");
this.MembershipApplication = page.locator("//h2[text()='Membership - Application']");
this.createAnAccountRenew = page.locator("//span[text()='Create an Account']");
this.contactSalesLink = page.locator("//a[contains(text(),'Contact Sales')]");
this.contactASTMHeader = page.locator("//h1[text()='Contact ASTM']");
this.popclose = page.locator("//*[@id='custom-close-overlay']");
this.digitalLibraryOverviewButton = page.locator("//a[contains(text(),'Digital Library Overview')]");
this.ASTMLogo = page.locator("//a[@href='https://stage.astm.org/']//img");
this.latestText = page.locator("//span[text()='The Latest']");
this.cartLinkAPI = page.locator("text=Cart");
this.cartLinkAPIText = page.locator("*[href*='checkout/cart']");
this.meetingsAndSymposiaLeftMenu = page.locator("//a[text()='Meetings & Symposia']");
this.clickOncontinueshoppingBtn = page.locator("//span[text()='Continue Shopping']");
this.metalsTestMethods = page.locator("//a[contains(text(), 'Metals Test Methods and Analytical Procedures')]");
this.editSearchBoxmobile = page.locator("#search-footer");
this.goButtonMobile = page.locator("//div[@class='input-group row m-0 astm-search']//button[@title='Search']");
this.firstTimeSearchCLoseInfo = page.locator("//div[@class='popover fade bs-popover-right show custom-overlay']//i[@id='custom-close-overlay']");
this.gCInAbout = page.locator("//nav[contains(@class,'astm-navbar')]//a[text()='Global Cooperation']");
this.continueShoppingButton = page.locator("//a[@class='continue primary btn astm-btn btn-primary']");
this.activeProductsAndServicesDefault = page.locator("//div[@class='webm']//a[@class='active' and @id='information' and contains(text(),'Products')]");
this.activeInformationDefault = page.locator("//div[@class='webm']//a[@id='information' and @class='active' and contains(text(), 'Information')]");
this.paginationInInfo = page.locator("//div[contains(@class,'mst-search')]/div[2]//ul[contains(@class,'pagination')]");
this.authors = page.locator("//nav[contains(@class,'astm-navbar')]//a[text()='Authors']");
this.searchInSAndP = page.locator("//input[@id='search-standards']");
this.ViewAll = page.locator("//a[text()='View All']");
this.STPLinkOne = page.locator("//div[@class='category-view']//p[1]/a");
this.SSMSInJournals = page.locator("//a[contains(text(),'SSMS')]");
this.TRLinkOne = page.locator("//div[@class='astm-type-body--lead']/p[3]/a");
this.COVIDInLeftMenu = page.locator("//span[text()='COVID 19']");
this.linkPersonnelCertification = page.locator("//a[contains(text(),'Personnel Certification')]");
this.linkEPD = page.locator("//a[contains(text(),'Environmental Product')]");
this.GDPRBanner = page.locator("//div[@id='onetrust-banner-sdk']");
this.GDPRRejectAll = page.locator("//button[@id='onetrust-reject-all-handler']");
this.GDPRAcceptAll = page.locator("//button[@id='onetrust-accept-btn-handler']");
this.GDPRCookieSettings = page.locator("//button[@id='onetrust-pc-btn-handler']");
this.AdditionalSettingsHeader = page.locator("//div[@class='ot-pc-header']");
this.AdditionalSettingsClose = page.locator("//button[@id='close-pc-btn-handler']");
this.OneTrustCookieClose = page.locator("//div[@id='onetrust-close-btn-container']/button");
this.CookieAlert = page.locator("//span[contains(text(),'cookies, including third party cookies')]");
this.PE_ContinuingEducationLink = page.locator("//nav[contains(@class,'astm-navbar')]//li//li/a[text()='PE Continuing Education']");
this.selectPlant = page.locator("#plant_select");
this.spinnerIcon = page.locator("div[data-component*='product_listing'] div.spinner");
this.certificate = page.locator(".card-text");
this.ReadOurFAQButton = page.locator("//*[contains(text(),'Read Our FAQ')]");
this.consumerrelatedarticlesHeading = page.locator("//h4[@class='astm-type-heading--h4 m-0 mb-2 mt-3'][text()='Consumer-Related Articles']");
this.newsreleasesHeading = page.locator("//h4[@class='astm-type-heading--h4 m-0 mb-2 mt-3'][text()='News Releases']");
this.meetingsandeventHeading = page.locator("//h4[@class='astm-type-heading--h4 m-0 mb-2 mt-3'][text()=' Meetings and Events']");
this.howtogetinvolvedHeader = page.locator("//h2[@class='astm-type-heading--h2 m-0 mb-2 mt-3 mt-md-0']");
this.mediapublicityrequestform = page.locator("//a[@href='https://qa.astm.org/get-involved/technical-committees/publicity-request.html']");
this.trainingandresourcesHeader = page.locator("//h2[@class='astm-type-heading--h2 m-0 mb-2 mt-3 mt-md-0']");
this.whyshouldijoin = page.locator("//h5[text()='Why should I join?']");
this.howtojoin = page.locator("//h5[text()='How to Join']");
this.financialassistanceforcustomer = page.locator("//h5[text()='Financial assistance for Consumers']");
this.requestfinancialassistanceButton = page.locator("//a[text()='Request Financial Assistance']");
this.becomeanastmmemberButton = page.locator("//a[text()='Become an ASTM Member']");
this.newmemberorientationandtrainingButton = page.locator("//a[text()='New Member Orientation & Training']");
this.accessreadingroomButton = page.locator("//a[text()='Access Reading Room']");
this.downloadtheconsumerguidebookButton = page.locator("//a[@href='https://public-admin-files-qa.s3.us-east-2.amazonaws.com/general/Consumer_Guide.pdf']");
this.kathiemorganimage = page.locator("//img[@src='https://qa.astm.org/media/wysiwyg/Kathie-Morgan-2022-1280px.jpg']");
this.everymemberhasavoice = page.locator("//h5[text()='Every Member Has a Voice']");
this.NCATTButton = page.locator("//*[contains(text(),'Learn More about NCATT')]");
this.LMAPC = page.locator("//*[contains(text(),'Learn More About Personnel Certification')]");
this.infographic = page.locator("//*[contains(text(),'View Infographic')]");
this.currentlyActive = page.locator("//span[contains(text(),'Currently Active')]");
this.ASTMheader = page.locator("//h1[contains(text(),'What is ASTM (ID: 2899')]");
this.selectfield = page.locator("//div[@class='action-select-wrap']//button[contains(text(),'Select')]");
this.filterpage = page.locator("//div[@class='data-grid-cell-content'][contains(text(),'Adjunct to D7611/D7611M Standard Practice for Coding Plastic Manufactured Articles for Resin Identification')]");
this.editoption = page.locator("//a[contains(text(),'Edit')]");
this.editpage = page.locator(".admin__fieldset-wrapper-content._hide");
this.verifyhowtogetinvolved = page.locator("//div[@class='data-grid-cell-content'][text()='How to Get Involved']");
this.EPD = page.locator("//*[contains(text(),'EPD for Martin Marietta (EPDs are generated using an enterprise software tool)')]");
this.CMSpage = page.locator(".admin__control-select");
this.classificationDropDown = page.locator("select[name='customer[classification]']");
this.customerTypeDropDown = page.locator("select[name='customer[customer_type]']");
this.SignInAdmin = page.locator(".mr-1");
this.IncomeMsgHeader = page.locator("//h1[contains(@id,'modal-title')]");
this.IncomeMsgClose = page.locator("//h1[contains(text(),'Incoming Message')]//following-sibling::button");
this.grandTotalInclTax = page.locator("#grand-total-include-tax > td.admin__total-amount >strong >span");
this.grandTotalIncTaxAfterSubmit = page.locator("//strong[text()='Grand Total (Incl.Tax)']/../../td[2]/strong/span");
this.grandTotalExcTaxAfterSubmit = page.locator("//strong[text()='Grand Total (Excl.Tax)']/../../td[2]/strong/span");
this.BookDealerDiscountOrderViewScreen = page.locator("tr.col-1 > td:nth-child(2) > span > span");
this.MemberDiscountOrderViewScreen = page.locator("tr:nth-child(2) > td:nth-child(2) > span");
this.shippingAndHandlingAfterSubmit = page.locator("tr.col-4 > td:nth-child(2) > span > span");
this.totalTaxAfterSubmit = page.locator("tbody > tr.summary-total > td:nth-child(2) > span");
this.lineItemSubTotal = page.locator("tbody > tr:nth-child(1) > td.col-subtotal > div > span");
this.lineItemSubDiscount = page.locator("tr:nth-child(1) > td.col-book-dealer-discount > span");
this.lineItemTax = page.locator("tr:nth-child(1) > td.col-tax-amount > span");
this.formatProductItem = page.locator("//*[@id='super-product-table']/tbody/tr/td/span");
this.AccountInformationTab = page.locator("//a[@id='tab_customer']");
this.AccountInfoCustName = page.locator("//h1[@class='page-title']");
this.ProductTitle = page.locator("(//span[@class='astm-type-body--lead']/b)[1]");
this.AllTrainingsHeader = page.locator("//*[@class='astm-type-heading--h2 mt-4']");
this.ProductsMenuOption = (productName: string) => page.locator(`//nav[contains(@class,'astm-navbar')]//a[contains(text(),'${productName}')]`);
this.continuebutton = page.locator("//button[contains(text(),'Agree and Continue')]");
this.okBtn = page.locator("//button[text()='OK']");
this.ARInvoiceType = page.locator("//select[@name='customer[ar_invoice_type]']");
this.ebsNumber_AccountInfoPage = page.locator("//input[@name='customer[ebs_account_number]']");
this.authorizationError = page.locator("//div[text()='Authorization Error']");
this.committeLink = page.locator("//a[text()='Committee']");
this.meetingsLink = page.locator("//a[text()='Meetings']");
this.addMeetingsequenceLink = page.locator("//button[text()='Add Meeting Sequence']");
this.addMeetingSeqMonthDropDown = page.locator("//div[@name='Month']");
this.collectionAttribute = page.locator("//input[@name='product[collection]']");
this.meetingTypeDropDown = page.locator("//div[@name='MeetingType']");
this.htmlCode = page.locator("//div[@class='placeholder-html-code']");
this.settings = page.locator("//ul[@class='pagebuilder-options-links']//li[3]");
this.htmlCodeInsert = page.locator("//textarea");
this.fullScreen = page.locator("//i[@title='Close Full Screen']");
this.saveBtn = page.locator("//button[text()='Save']");
this.WI_FullList_link = page.locator("//a[contains(@href,'work-items-full-list')]");
this.WI_FullList_linkHdr = page.locator("//h2[contains(text(),'Work Items- Full List')]");
this.cookieRejectAll = page.locator("//button[text()='Cookies Settings']//following-sibling::button[text()='Reject All']");
this.WI_FullList_RequiredWI = (wiNumber: string) => page.locator(`//li[@class='mb-3']/a[contains(text(),'${wiNumber}')]`);
this.sendActivationEmailToggleInput = page.locator("//input[@name='customer[send_membership_activation_email]']");
this.HazardousWarningText = page.locator("//span[contains(text(),'One or more of the products in your cart contains a hazardous material')]");
this.useSelectedAddressBTN = page.locator("//span[contains(text(),'Use Selected Address')]/parent::button");
this.AddmodelBoxText = page.locator("//div[contains(text(),'We can not')]");
this.useSelAddressTitleMagento = page.locator("(//h1[@class='modal-title'])[4]");
this.AddressEnteredRadio = page.locator("//input[@id='entered']");
this.UseSelAddText = page.locator("//div[contains(text(),'We have slightly modified')]");
this.confirmAddressValidation = page.locator("//div[@class='address-modal-description']");
this.wrongAddressValidation = page.locator("//div[contains(text(),'Do you want to proceed')]/..");
this.useSelAddressTitle = page.locator("//div[contains(text(),'We can not')]/parent::div/parent::div/descendant::h1");
this.ContinueBtn = page.locator("//button[contains(@class,'action-accept')]");
this.researchReportProduct = page.locator("//*[@id='product-search-container']/div[1]/div/h4/a");
this.addToCartButton = page.locator("//button[@title='Add to Cart']");
this.ResearchReportNames = page.locator("//h2/button");
this.SearchButton = page.locator("//*[@id='search']");
this.committeDesginationLnks = page.locator("//table[@id='customGrid']//tr//a");
this.addMeetingSeqcancelBtn = page.locator("//button[text()='Cancel']");
this.IssOrderPagechekbox = page.locator("//tr[@id='row_address_validation_enable_on_order']/descendant::input");
this.Enablechekbox = page.locator("//tr[@id='row_address_validation_enable']/descendant::input");
this.IssOrderPageDropdown = page.locator("//tr[@id='row_address_validation_enable_on_order']/descendant::select");
this.saveConfig = page.locator("//span[contains(text(),'Save Config')]");
this.contactFirstName = page.locator("(//input[@name='first_name'])[2]");
this.contactLastName = page.locator("(//input[@name='last_name'])[2]");
this.contactEmail = page.locator("(//input[@name='email'])[2]");
this.TPTLearner = page.locator("//fieldset[@class='admin__fieldset']/div[2]/div/div/label");
this.billTo = page.locator("//span[text()='Bill to']//following::div[@class='admin__actions-switch'][1]");
this.shipTo = page.locator("//span[text()='Bill to']//following::div[@class='admin__actions-switch'][2]");
this.cancelButtonOnAlert = page.locator("//footer[@class='modal-footer']//span[text()='Cancel']");
this.selectCreditCard = page.locator("//input[@id='p_method_braintree']");
this.creditcardNo = page.locator("//input[@id='credit-card-number']");
this.expirationMonth = page.locator("//input[@id='expiration-month']");
this.expirationYear = page.locator("//input[@id='expiration-year']");
this.cvvNumber = page.locator("//input[@id='cvv']");
this.iframeccnumber = "braintree-hosted-field-number";
this.iframeExpMonth = "braintree-hosted-field-expirationMonth";
this.iframeExpYear = "braintree-hosted-field-expirationYear";
this.iframecvv = "braintree-hosted-field-cvv";
this.headerReadingRoom = page.locator("//h1[@data-testid='greeting-heading']");
this.studentPayment = page.locator("//dl[@class='admin__payment-methods control']/descendant::label");
this.inResidenceTrainingPrograms = page.locator("(//a[text()='In-Residence Training Programs'])[1]");
this.onlineTrainingLink = page.locator("//span[text()='Online Training']");
this.internationalPartnersLink = page.locator("//span[text()='International Partners']");
this.uaeChapterLink = page.locator("//span[text()='UAE Chapter']");
this.searchptp = page.locator("//input[@id='search']");
this.searchBtnptp = page.locator("(//button[@type='button'])[3]");
this.ptpProduct = page.locator("(//a[@href='https://stage.astm.org/ptpislg2023.html'])[2]");
this.ptpOil = page.locator("(//a[@href='https://stage.astm.org/ptpisto2023.html'])[4]");
this.contact1 = page.locator("(//*[text()='Contact'])[2]");
this.TechnicalCommitteeFullList = page.locator("//a[@href='/get-involved/technical-committees/committee-all']");
this.TechnicalCommitteProduct = page.locator("//a[@href='https://stage.astm.org/get-involved/technical-committees/committee-a01']");
this.standardProduct = page.locator("//a[@href='https://stage.astm.org/get-involved/technical-committees/committee-a01/subcommittee-a01']");
this.subcommitteStandard = page.locator("//a[@href='https://stage.astm.org/get-involved/technical-committees/committee-a01/subcommittee-a01/jurisdiction-a0101']");
this.searchWorkItem = page.locator("//a[text()=' WK85700 ']");
this.home = page.locator("//a[@title='Go to Home Page']");
this.committeAward = page.locator("(//div[@class='mst-search__index-title']/a)[1]");
this.tenantMarketinghdr = page.locator("(//div[@class='mst-search__index-title']/a)[1]");
this.technicalCommitteeAwards = page.locator("https://stage.astm.org/catalogsearch/result/index/?index=8&q=Technical+Committee+Awards+");
this.otherPublisher = page.locator("(//a[text()='Other Publishers'])[1]");
this.downloadCompassEbook = page.locator("//a[@class='btn-contact btn astm-btn btn-primary mt-3']");
this.requestDemo = page.locator("(//a[text()='Request Demo'])[1]");
this.ANSIReview = page.locator("//a[@href='https://stage.astm.org/get-involved/technical-committees/ansi-review']");
this.workItem = page.locator("//a[text()='2021/09/17']");
this.lightSportAircraft = page.locator("(//*[contains(text(),'Light Sport Aircraft')])[2]");
this.searchTitle = page.locator("(//div[@class='search-title'])[1]");
this.homeNavigation = page.locator("//a[text()='Home']");
this.standardsAndNavigation = page.locator("(//a[@href='https://stage.astm.org/products-services/standards-and-publications.html'])[5]");
this.standardsProductNavigation = page.locator("(//a[@href='https://stage.astm.org/products-services/standards-and-publications/standards.html'])[3]");


      
  }

 



}