import { Page, Locator, expect,test } from '@playwright/test';
import { stepLogger } from '../utils/logger';
import { attachScreenshot } from '../utils/reportUtils';

export class HomePageSubscriptionpage {

     readonly inputTextFieldOfSearchTxtArea: Locator;
  readonly designationSearch: Locator;
  readonly compassPointAdmin: Locator;
  readonly closeBtnOfAIpopup: Locator;
  readonly leftMenuSubscriptionsSubLinks: Locator;
  readonly semanticSearch_Button: Locator;
  readonly welcomeBackHeaderOnHomePage: Locator;
  readonly header: Locator;
  readonly recentlyAccessedTab: Locator;
  readonly welcomeBackHeader: Locator;
  readonly trackerTab: Locator;
  readonly trackerTabActive: Locator;
  readonly favoritesTab1: Locator;
  readonly favoritesTab: Locator;
  readonly subscriptionsTab: Locator;
  readonly subscriptions_Tab: Locator;
  readonly tiles_text: Locator;
  readonly tripTricks: Locator;
  readonly deleteIcon: Locator;
  readonly DatesNotes: Locator;
  readonly DocumentsNotes: Locator;
  readonly technicalCommittees: Locator;
  readonly membership: Locator;
  readonly MYASTM: Locator;
  readonly meetingSymposia: Locator;
  readonly myCommittees: Locator;
  readonly publishWithASTM: Locator;
  readonly translatedWelcomeBack: Locator;
  readonly esDropdown: Locator;
  readonly ruDropdown: Locator;
  readonly arabicMenu: Locator;
  readonly trackerMenu: Locator;
  readonly headerHome: Locator;
  readonly compassNotes: Locator;
  readonly recentlyAccesseddocs: Locator;
  readonly readingRoomTipsTricksHeader: Locator;
  readonly needMoreAssistance: Locator;
  readonly needMoreAssistance_Content: Locator;
  readonly learnMore_CompassNotes: Locator;
  readonly versionComparison: Locator;
  readonly versionComparison_Message: Locator;
  readonly learnMore_versionComparison: Locator;
  readonly compasspointstab: Locator;
  readonly privacyPolicy: Locator;
  readonly policies: Locator;
  readonly myASTMOption: Locator;
  readonly menu: Locator;
  readonly close: Locator;
  readonly backToGroupTiles: Locator;
  readonly MenuTracker: Locator;
  readonly Groups_Menu: Locator;
  readonly clickOnRelatedDoc: Locator;
  readonly documentTitle: Locator;
  readonly DescriptionTile: Locator;
    readonly membersCount: Locator;
  readonly documentsCount: Locator;
  readonly standardReferencesTitle: Locator;
  readonly standardReferencesDropdown: Locator;
  readonly standardOperatingProceduresTitle: Locator;
  readonly standardOperatingProceduresDropdown: Locator;
  readonly designationColumn: Locator;
  readonly designationColumn_SOP: Locator;
  readonly titleColumn: Locator;
  readonly productCodeCol: Locator;
  readonly titleColumn_SOP: Locator;
  readonly firstTitle: Locator;
  readonly firstTitle_SOP: Locator;
  readonly clickOnRelatedContent: Locator;
  readonly clickOnTitle: Locator;
  readonly ASTMlogo: Locator;
  readonly paraText: Locator;
  readonly cookie_close: Locator;
  readonly clickOnTitleGroup: Locator;
  readonly titleOfGroup: Locator;
  readonly members: Locator;
  readonly titleEdit: Locator;
  readonly DescriptionEdit: Locator;
  readonly deleteIconNotes: Locator;
  readonly noNotes: Locator;
  readonly ASTMlogoMobile: Locator;
  readonly APILogo: Locator;
  readonly AENORLogo: Locator;
  readonly ASTMLogo: Locator;
  readonly IESLogo: Locator;
  readonly AWWALogo: Locator;
  readonly noResults: Locator;
  readonly CGALogo: Locator;
  readonly clickOnLangDropDown: Locator;
  readonly languageContainer: Locator;
  readonly Language: Locator;
  readonly StayOnPageBtn: Locator;
  readonly DefaultLanguage: Locator;
  readonly magnifyingGlass: Locator;
  readonly magnifyingGlassSub: Locator;
  readonly username: Locator;
  readonly usernameOptions: Locator;
  readonly Myaccount: Locator;
  readonly accountPage: Locator;
  readonly OtherVersions: Locator;
  readonly myAccount: Locator;
  readonly CompareVersions: Locator;
  readonly checkbox2_CompareVersions: Locator;
  readonly compareButton: Locator;
  readonly compareButton_Disabled: Locator;
  readonly compareVersionOptions: Locator;
  readonly changeListIcon: Locator;
  readonly changeList: Locator;
  readonly print: Locator;
  readonly closeComparisonButton: Locator;
  readonly recentlyUpdatedTab: Locator;
  readonly publisher: Locator;
  readonly myAccountHeader: Locator;
  readonly destinationNo: Locator;
  readonly document: Locator;
  readonly status: Locator;
  readonly lastUpdate: Locator;
  readonly searchDropdown: Locator;
  readonly searchDropdownAll: Locator;
  readonly searchDropdownAlltext: Locator;
  readonly searchDropdownMySubscription: Locator;
  readonly searchBox: Locator;
  readonly twitterLink: Locator;
  readonly facebookLink: Locator;
  readonly youtubeLink: Locator;
  readonly linkedinLink: Locator;
  readonly instagramLink: Locator;
  readonly astmRSSLink: Locator;
  readonly Copyright_PermissionLink: Locator;
  readonly helpDropdown: Locator;
  readonly helpDropdown1: Locator;
  readonly supportFAQs: Locator;
  readonly training: Locator;
  readonly recentlyUpdatedCardContent: Locator;
  readonly DocumentHeader: Locator;
  readonly Designation: Locator;
  readonly DocStatus: Locator;
  readonly TrackDocument: Locator;
  readonly trackIcon: Locator;
  readonly favoriteIcon: Locator;
  readonly UntrackDocument: Locator;
  readonly Downloadwithcompasspoints: Locator;
  readonly AddToFavorites: Locator;
  readonly RemoveFavorites: Locator;
  readonly ToggleSwitches: Locator;
  readonly Download: Locator;
  readonly PDF: Locator;
  readonly trainingvideo: Locator;
  readonly pdfPages: Locator;
  readonly SearchFilter: Locator;
  readonly HTMLActive: Locator;
  readonly HTML: Locator;
  readonly trainingAndVideos: Locator;
  readonly eLearning: Locator;
  readonly designation_HTML: Locator;
  readonly organization_Caveat: Locator;
readonly ViewAllTracked: Locator;
readonly trackedDocument: Locator;
readonly MenuHome: Locator;
readonly CustomCollections: Locator;
readonly SubscriptionUsage: Locator;
readonly AENORlogo: Locator;
readonly SubscriptionsMenu: Locator;
readonly TrackerMenu: Locator;
readonly FavoritesMenu: Locator;
readonly FavoritesHeader: Locator;
readonly NotesHeader: Locator;
readonly notesFilter: Locator;
readonly clickOnNew: Locator;
readonly notesDoc: Locator;
readonly clickOnMigrated: Locator;
readonly noMigratedNotes: Locator;
readonly PoweredBy: Locator;
readonly AWWAFooterLogo: Locator;
readonly CompareModalCheckbox: Locator;
readonly DocumentHeading: Locator;
readonly CompareButton: Locator;
readonly CloseCompareButton: Locator;
readonly closeCompareModal: Locator;
readonly DownloadRedlinedButton: Locator;
readonly EditOpton: Locator;
readonly maskclass: Locator;
readonly stdTrackerHeader: Locator;
readonly searchText: Locator;
readonly allSearch_RadioButton: Locator;
readonly keyword_RadioButton: Locator;
readonly designation_RadioButton: Locator;
readonly mySubscription_RadioButton: Locator;
readonly resultsHeader: Locator;
readonly searchFeedback: Locator;
readonly searchFeedback_popup: Locator;
readonly searchedHeader: Locator;
readonly question1: Locator;
readonly feedback1: Locator;
readonly question2: Locator;
readonly additionalFeedback: Locator;
readonly searchTextSub: Locator;
readonly hyperLink: Locator;
readonly hyperLink1: Locator;
readonly hyperLink_HTML: Locator;
readonly confirm: Locator;
readonly replacedBy: Locator;
readonly contentBadge: Locator;
readonly serpFirstDocument: Locator;
readonly pdfDefault: Locator;
readonly versionFirstDocument: Locator;
readonly versionDropdown: Locator;
readonly languageFirstDocument: Locator;
readonly translatedLang: Locator;
readonly serpResults: Locator;
readonly clickOnDocument: Locator;
readonly trackerCardContent: Locator;
readonly menuTracker: Locator;
readonly trackerRow: Locator;
readonly trackCheckBox: Locator;
readonly WhatStandard: Locator;
readonly AccountSelect: Locator;
readonly subscriptionTab: Locator;
readonly accountDropdown: Locator;
readonly Signout: Locator;
readonly HomepageTabs: Locator;
readonly ViewAllFavorites: Locator;
readonly ViewAllTrackedDocs: Locator;
readonly MyFavoritesHeader: Locator;
readonly favoriteDocument: Locator;
readonly deleteFavoriteDocument: Locator;
readonly delete_Popup: Locator;
readonly myFavoritesDescription: Locator;
readonly noRecordsFound: Locator;
readonly ViewAlltTracked: Locator;
readonly NextPage: Locator;
readonly VersionDisclaimer: Locator;
readonly WTO: Locator;
readonly VideoTutorials: Locator;
readonly VideoTutorialsLink: Locator;
readonly VideosPageTitle: Locator;
readonly VideoTitle: Locator;
readonly playVideo: Locator;
readonly pauseVideo: Locator;
readonly videos: Locator;
readonly WithdrawnLink: Locator;
readonly AENORPremiumLogo: Locator;
readonly DownloadPDF: Locator;
readonly PDFTronView: Locator;
readonly AenorsearchBar: Locator;
readonly AenorDocumentUNE139802: Locator;
readonly Download_PDFtab: Locator;
readonly awwaDesign: Locator;
readonly CreateGroups: Locator;
readonly GroupName: Locator;
readonly DeleteGroup: Locator;
readonly Close: Locator;
readonly update: Locator;
readonly crossClose: Locator;
readonly NavBarClose: Locator;
readonly Next: Locator;
readonly TextunderDescription: Locator;
readonly Back: Locator;
readonly CreateGroupIcon: Locator;
readonly GroupNameTextBox: Locator;
readonly GroupDescriptionTextBox: Locator;
readonly AddGroupMember: Locator;
readonly SearchBar_AddMember: Locator;
readonly MagnifyingGlass_AddMember: Locator;
readonly magnifyingGlass_EditMember: Locator;
readonly magnifyingGlass_Documents: Locator;
readonly testingMigration: Locator;
readonly RightArrow_AddMember: Locator;
readonly SelectAll_AddMember: Locator;
readonly IESQA_AddMember: Locator;
readonly AenorSub_AddMember: Locator;
readonly AWWAQA_AddMember: Locator;
readonly rightSideMover: Locator;
readonly groupMemberDocument: Locator;
readonly compassMembersDocument: Locator;
readonly comprehensiveList: Locator;
readonly Threedots_GroupTile: Locator;
readonly Edit_GroupTile: Locator;
readonly SearchBar_AddDocument: Locator;
readonly AddButton_AddDocWindow: Locator;
readonly CloseButton_AddDocWindow: Locator;
readonly Create: Locator;
readonly subscriptionsTabHomePage: Locator;
readonly subscriptionsTabASTMLink: Locator;
readonly editGroup: Locator;
readonly membersName: Locator;
readonly CopyrightText: Locator;
readonly tilesContainer: Locator;
readonly groupSuccessUpdated: Locator;
readonly groupAddDocument: Locator;
readonly emailTitle: Locator;
readonly emailSubject: Locator;
readonly emailMessage: Locator;
readonly deletePopUp: Locator;
readonly emailCheckBox: Locator;
readonly deleteTitle: Locator;
readonly elementInput: Locator;
readonly ShareOption: Locator;
readonly moreEmail: Locator;
readonly homeGroup: Locator;
readonly SearchBar_Modal: Locator;
readonly GeneralDocuement: Locator;
readonly More: Locator;
readonly Magnifyglass_Modal: Locator;
readonly NoMatch: Locator;
readonly IlluminanceTables: Locator;
readonly Elearning: Locator;
readonly NoAccess: Locator;
readonly NoAccess_api: Locator;
readonly NoAccessElearning: Locator;
readonly CloseNoAccess: Locator;
readonly supplementalDocuments: Locator;
readonly RelatedLinks: Locator;
readonly content: Locator;
readonly AstmInternational: Locator;
readonly modalEmailAddress: Locator;
readonly magnifyingGlassEmailAddress: Locator;
readonly EmailAddressCheck: Locator;
readonly seeMore: Locator;
readonly shareEmail: Locator;
readonly WorkItem: Locator;
readonly Publisher_WorkItem: Locator;
readonly WorkItemNo: Locator;
readonly DateInitiated: Locator;
readonly StatusofWorkItem: Locator;
readonly TechnicalContact: Locator;
readonly dropdown: Locator;
readonly docshareme: Locator;
readonly Mysharedoc: Locator;
readonly Mydoc: Locator;
readonly designation: Locator;
readonly pagination: Locator;
readonly nextpagination: Locator;
readonly chevron_WI: Locator;
readonly TC_MWI: Locator;
readonly PubWI: Locator;
readonly chevronup: Locator;
readonly WIModaltitle: Locator;
readonly WIModalbody: Locator;
readonly Help: Locator;
readonly moreResource: Locator;
readonly docShareWithMe: Locator;
readonly UserResourcePage: Locator;
readonly leftNavigationLink: Locator;
readonly LTSLink: Locator;
readonly LTS: Locator;
readonly CaratLTS: Locator;
readonly LTSdetails: Locator;
readonly DocumentC: Locator;
readonly DesignationC: Locator;
readonly TitleC: Locator;
readonly DocTable: Locator;
readonly firstLast: Locator;
readonly PDFnoNotes: Locator;
readonly Welcometitle: Locator;
readonly Accountid: Locator;
readonly DocType: Locator;
readonly MARCrecords: Locator;
readonly clickOnMARCrecords: Locator;
readonly listOfJournals: Locator;
readonly DeleteIcon: Locator;
readonly Delete: Locator;
readonly PDFdownloadArrow: Locator;
readonly DownloadRedlinedArrow: Locator;
readonly DeleteIcon_AWWA_Tracker: Locator;
readonly SABADoc: Locator;
readonly DownloadOption: Locator;
readonly ZipDownloadOption: Locator;
readonly ZipDownloadOption_api: Locator;
readonly langDropDownDoc: Locator;
readonly langClick: Locator;
readonly UserGuideLink: Locator;
readonly HomeLink: Locator;
readonly HomeLogo: Locator;
readonly ResultTypeDropdown: Locator;
readonly DocumentDropdown: Locator;
readonly Proceeding_ResultType: Locator;
readonly CategoryLinks: Locator;
readonly SecondaryListDropdown_Category: Locator;
readonly SecondaryList_Category: Locator;
readonly Active_Refinment: Locator;
readonly ActiveDocuments: Locator;
readonly DocumentDesignation: Locator;
readonly CGADocumentDropdown: Locator;
readonly Withdrawn_Refinment: Locator;
readonly WithdrawnDocuments: Locator;
readonly CGADocumentRefinment: Locator;
readonly documentTypeVideo: Locator;
readonly standardVideo: Locator;
readonly videosOnSerp: Locator;
readonly ExplorationAndProduction: Locator;
readonly SecondaryList: Locator;
readonly TranslationDropdown: Locator;
readonly OtherVersionDropdown: Locator;
readonly OtherVersionList: Locator;
readonly TranslatedStandard: Locator;
readonly SwitchAccountInHeader: Locator;
readonly selectAccount: Locator;
readonly ButtonOnSelectAccountScreen: Locator;
readonly WelcomeBackAfteraccountSelection: Locator;
readonly signOut: Locator;
readonly CompareVersionTileMessage: Locator;
readonly CGAAddresse: Locator;
readonly APIErrorMessage: Locator;
readonly listUnderSearchBox: Locator;
readonly TechnicalReportRefinment: Locator;
readonly LightingLibraryContentsLink: Locator;
readonly ReferenceRetriever: Locator;
readonly hpdf: Locator;
readonly trackerDocuments: Locator;
readonly favoritesDocument: Locator;
readonly annotate: Locator;
readonly annotateActive: Locator;
readonly viewNotes: Locator;
readonly commentsBox: Locator;
readonly notesInDocuments: Locator;
readonly notesPopUp: Locator;
readonly EditInNotes: Locator;
readonly EditModal: Locator;
readonly existingNotes: Locator;
readonly SaveNotesButton: Locator;
readonly textAreaNotesModal: Locator;
readonly RIS: Locator;
readonly SelectedTechnicalPapers: Locator;
readonly Export_Button: Locator;
readonly CitationInfoIcon: Locator;
readonly MyAccounts: Locator;
readonly firstNameLabel_PersonalInfoPage: Locator;
readonly middleNameLabel_PersonalInfoPage: Locator;
readonly lastNameLabel_PersonalInfoPage: Locator;
readonly emailLabel_PersonalInfoPage: Locator;
readonly compassEditBtn_PersonalInfoPage: Locator;
readonly compassLink_PersonalInfoPage: Locator;
readonly OrganisationCompass: Locator;
readonly QAOrganisationCompass: Locator;

readonly OrganisationCompassIES: Locator;
readonly OrganisationCompassSelect: Locator;
readonly OrganisationCompassSelectCGA: Locator;
readonly OrganisationCompassSelectAWWA: Locator;
readonly OrganisationCompassSelectAPI: Locator;
readonly OrganisationCompassSelectAenor: Locator;
readonly PersonalInformation: Locator;
readonly OrgCompass: Locator;
readonly orgDropdown_compassLink: Locator;
readonly AccountCompass: Locator;
readonly cancelBtn_additionalOrganization: Locator;
readonly saveBtn_additionalOrganization: Locator;
readonly accountNumberLabelCompassLink: Locator;
readonly additionalOrgLbl_CompassLink: Locator;
readonly additionalOrganisationTextField_CompassLink: Locator;
readonly addOrgVal_CompassLink: Locator;
readonly editLinkUnderCompassLabel: Locator;
readonly accountNoValueUnderCompassLink: Locator;
readonly passwordLink_ProfilePage: Locator;
readonly resetPwdSuccessMsg_ProfilePage: Locator;
readonly resetPwdSuccessMsgCloseBtn_ProfilePage: Locator;
readonly footerSectionHomeLink: Locator;
readonly footerSectionContactLink: Locator;
readonly contactLinkContactPageNotFoundMsg: Locator;
readonly contactLinkContactPageNotFoundMsg_APITenant: Locator;
readonly footerLinks: Locator;
readonly addressOfAPIFromFooterSection: Locator;
readonly addressOfAENORFromFooterSection: Locator;
readonly copyrightYearWithASTMAddressFromFooterSection: Locator;
readonly copyrightYearWithASTMAddressFromFooterSection_ASTMTenant: Locator;
readonly closeBtn_invalidPwdErrMsg: Locator;
readonly newPasswordInputField_PasswordLink: Locator;
readonly confirmPassword_PasswordLink: Locator;
readonly savePasswordBtn_PasswordLink: Locator;
readonly passwordHeader_UnderPasswordLink: Locator;
readonly currentPasswordInputField_PasswordLink: Locator;
readonly currentPasswordInvalidErrorMsg_PasswordLink: Locator;
readonly StageOrganisationCompass: Locator;
readonly inputCompare: Locator;
readonly MenuSubscription: Locator;
readonly MenuASTM: Locator;
readonly closeNavBar: Locator;
readonly DocumentDetails: Locator;
readonly cookieCloseButton: Locator;
readonly buttonSelect: Locator;
readonly agreeAndContinue: Locator;
readonly SignInNew: Locator;
readonly VideoTutorialLink: Locator;
readonly ViewUserVisibility: Locator;
readonly AddUserMAE: Locator;
readonly TestAutomationGroup: Locator;
readonly AddDocuments: Locator;
readonly GroupAddDocument: Locator;
readonly Add: Locator;
readonly AddDocumentSearchBar: Locator;
readonly Trash: Locator;
readonly IECTestAutomationGroup: Locator;
readonly RightSideDocument: Locator;
readonly SSOUsername: Locator;
readonly SSOPassword: Locator;
readonly SSOSignIN: Locator;
readonly UserGuideLinkEnglish: Locator;
readonly UserGuideLinkSpanish: Locator;
readonly Contact: Locator;
readonly PrivacyPolicyFooter: Locator;
readonly PoliciesFooter: Locator;
readonly Copyright_Permissions: Locator;
readonly CustomCollectionsHeader: Locator;
readonly customCollectionsLinks: Locator;
readonly documentStatus: Locator;
readonly documentDesignation: Locator;
readonly designation_doc: Locator;
readonly publisherDropdown: Locator;
readonly WohlersReportRecentlyAccessed: Locator;
readonly AddShareEmail: Locator;
readonly SearchEMail: Locator;
readonly AddEmail: Locator;
readonly ShareEmail: Locator;
readonly TechnicalCommittees: Locator;
readonly Membership: Locator;
readonly favoritesDocLinks: Locator;
readonly deleteFavConfirm: Locator;
readonly TrackedDocLinks: Locator;
readonly VersionDDItems: Locator;
readonly VersionDDLink: Locator;
readonly MyAccount: Locator;
readonly emailinMyAccountPage: Locator;
readonly switchAcc: Locator;
readonly switchAccHeading: Locator;
readonly docsShared: Locator;
readonly nodocsharemsg: Locator;
readonly sharedDocrows: Locator;
readonly NavMenuLinks: Locator;
readonly HeaderLinksDD: Locator;
readonly CitationModelHeader: Locator;
readonly Pdfsearch: Locator;
readonly HTMLCompateDisclaimer: Locator;
readonly NavMenuTrackerLink: Locator;





     constructor(page: Page) {

    this.inputTextFieldOfSearchTxtArea = page.locator("#search_input_mainpage");
    this.designationSearch = page.locator("//label[text()='Designation']");
    this.compassPointAdmin = page.locator("//a[text()='Compass Points Admin']");
    this.closeBtnOfAIpopup = page.locator("//button[@type='button' and @class='close']");
    this.leftMenuSubscriptionsSubLinks = page.locator("//p[contains(@class,'major-sub-menu')]/a");
    this.semanticSearch_Button = page.locator("//input[@id='SEMANTICSEARCH_mainpage']");
    this.welcomeBackHeaderOnHomePage = page.locator("//h1[contains(@class,'wlc-title')]");
    this.header = page.locator("//h2[@class='astm-header1 wlc-title']//span");
    this.recentlyAccessedTab = page.locator("//span[contains(text(),'Recently Accessed')]//ancestor::p");
    this.welcomeBackHeader = page.locator("//*[contains(text(),'Welcome')]");
    this.trackerTab = page.locator("//span[contains(text(),'Tracker')]//ancestor::p");
    this.trackerTabActive = page.locator("//p[contains(@class,'active')]");
    this.favoritesTab1 = page.locator("//span[contains(text(),'Favorites')]//ancestor::p");
    this.favoritesTab = page.locator("//span[contains(text(),'Favorites')]//ancestor::p/span");
    this.subscriptionsTab = page.locator("(//span[contains(text(),'Subscriptions')]//ancestor::p");
    this.subscriptions_Tab = page.locator("//p[@class='tab astm-type-heading--h6']//span[text()='Subscriptions']");
    this.tiles_text = page.locator("//p[@class='noPaddingMargin astm-type-body--lead bold']");
    this.tripTricks = page.locator("//span[text()='Tips & Tricks']");
    this.deleteIcon = page.locator("//i[@class='astm-icon far fa-trash-alt pointer-cursor']");
    this.DatesNotes = page.locator("//td[@class='astm-table-td astm-type-body--lead date-column']");
    this.DocumentsNotes = page.locator("//td[@class='astm-table-td astm-type-body--lead document-column']//span//a");
    this.technicalCommittees = page.locator("//span[contains(text(),'ASTM Community')]/parent::p/parent::div//following-sibling::div//p//a[contains(text(),'Technical Committees')]");
    this.membership = page.locator("//span[contains(text(),'ASTM Community')]/parent::p/parent::div//following-sibling::div//p//a[contains(text(),'Join as a Member')]");
    this.MYASTM = page.locator("//span[contains(text(),'ASTM Community')]/parent::p/parent::div//following-sibling::div//p[contains(text(),'MyASTM')]");
    this.meetingSymposia = page.locator("//span[contains(text(),'ASTM Community')]/parent::p/parent::div//following-sibling::div//p[contains(text(),'Meetings & Symposia')]");
    this.myCommittees = page.locator("//span[contains(text(),'ASTM Community')]/parent::p/parent::div//following-sibling::div//a[contains(text(),'My Committees')]");
    this.publishWithASTM = page.locator("//span[contains(text(),'ASTM Community')]/parent::p/parent::div//following-sibling::div//p//a[contains(text(),'Publish with ASTM')]");
    this.translatedWelcomeBack = page.locator("//div/div[2]/h1");
    this.esDropdown = page.locator("//button[@value='es']");
    this.ruDropdown = page.locator("//option[@value='ru']");
    this.arabicMenu = page.locator("//a[@data-testid='brandbutton']");
    this.trackerMenu = page.locator("//a[@href='https://stage-tracker.astm.org']");
    this.headerHome = page.locator("//h1[@class='astm-type-heading--h5 astm-type-heading--h5-bold wlc-title wlc-title-margin']");
    this.compassNotes = page.locator("//h1[contains(text(),'Recently Updated & Recently Accessed')]");
    this.recentlyAccesseddocs = page.locator("//div[@class='card-title']");
    this.readingRoomTipsTricksHeader = page.locator("//span[text()='Reading Room Tips and Tricks']");
    this.needMoreAssistance = page.locator("//h1[text()='Need More Assistance?']");
    this.needMoreAssistance_Content = page.locator("(//div[@class='card-wrapper astm-card tips-tricks-card card']/p)[2]");
    this.learnMore_CompassNotes = page.locator("(//a[text()='Learn more'])[1]");
    this.versionComparison = page.locator("//h1[contains(text(),'Compare Version')]");
    this.versionComparison_Message = page.locator("//p[text()='Easily compare the differences between active and historical standards in PDF format.']");
    this.learnMore_versionComparison = page.locator("(//a[text()='Learn more'])[2]");
    this.compasspointstab = page.locator("//*[@id='app']/div[1]/div[2]/div[1]/div[5]/div/div[1]/button[2]");
    this.privacyPolicy = page.locator("//a[contains(@href,'/POLICY/privacy_policy.html')]");
    this.policies = page.locator("//a[contains(@href,'/prpolicy.html')]");
    this.myASTMOption = page.locator("//*[@class='dropdown-menu dropdown-menu-right show']//a[@id='my-astm']");
    this.menu = page.locator("//span[text()='Menu']//ancestor::a");
    this.close = page.locator("//*[@id='sidebar']/p[1]");
    this.backToGroupTiles = page.locator("//i[@class='astm-icon far fa-chevron-left']//parent::a");
    this.MenuTracker = page.locator("//a[@class='color-secondary sidebar-link'and text()=\"Tracker\"]");
    this.Groups_Menu = page.locator("//a[@class=\"color-secondary sidebar-link\" and text()='Groups']");
    this.clickOnRelatedDoc = page.locator("//span[text()='Related Content']//parent::span//parent::p");
    this.documentTitle = page.locator("//p[@class='astm-type-heading--h3 document-title']");
    this.DescriptionTile = page.locator("//div[@class='card-body']//p[@class='astm-type-body--lead card-description']");
    this.membersCount = page.locator("//div[@class='card-title']//span[@class='astm-type-body members-count']");
    this.documentsCount = page.locator("//div[@class='card-title']//span[@class='astm-type-body documents-count']");
    this.standardReferencesTitle = page.locator("//b[text()='Standard References']");
    this.standardReferencesDropdown = page.locator("//*[@id='cited']/span/span");
    this.standardOperatingProceduresTitle = page.locator("//b[text()='Standard Operating Procedures']");
    this.standardOperatingProceduresDropdown = page.locator("//*[@id='sop']/span/span");
    this.designationColumn = page.locator("//th[text()='Designation']");
    this.designationColumn_SOP = page.locator("(//th[text()='Designation'])[2]");
    this.titleColumn = page.locator("//th[text()='Title']");
    this.productCodeCol = page.locator("//th[text()='Product Code']");
    this.titleColumn_SOP = page.locator("(//th[text()='Title'])[2]");
    this.firstTitle = page.locator("//a[@class='astm-type-body--lead blue-75 related-item']");
    this.firstTitle_SOP = page.locator("//*[@id='app-view-container']/div/div/div[2]/div/div/div[5]/div/div[2]/div[2]/table/tbody/tr/td[2]/a");
    this.clickOnRelatedContent = page.locator("//span[text()='Related Content']");
    this.clickOnTitle = page.locator("//p[@class='astm-type-heading--h3 document-title']");
    this.ASTMlogo = page.locator("//a[@style='background-image: url(\"../../../../content/logos/astm.svg\");']");
    this.paraText = page.locator("//div[@class='col-md-6 col-lg-4']//div[@class='footer-container']//p");
    this.cookie_close = page.locator("//i[@class='astm-icon astm-icon--white far fa-times']");
    this.clickOnTitleGroup = page.locator("//a[@class='astm-link astm-type-heading--h5-bold']");
    this.titleOfGroup = page.locator("//h1[@class='astm-type-heading--h5 astm-type-heading--h5-bold wlc-title group-detail-header']");
    this.members = page.locator("//div[@class='group-detail-member']//h1");
    this.titleEdit = page.locator("//div[@class='group-detail-content-heading row']//span[@class='astm-type-body edit']");
    this.DescriptionEdit = page.locator("//div[@class='group-detail-description']//span[@class='astm-type-body edit']");
    this.deleteIconNotes = page.locator("//i[@class='astm-icon far fa-trash-alt pointer-cursor']//parent::td");
    this.noNotes = page.locator("//span[text()='No Notes' and @class='no-notes-title astm-type-heading--h5']");
    this.ASTMlogoMobile = page.locator("//a[@class='user-logo']");
    this.APILogo = page.locator("//a[contains(@style,'api')]");
    this.AENORLogo = page.locator("//a[contains(@style,'AENOR')]");
    this.ASTMLogo = page.locator("//a[contains(@style,'astm')]");
    this.IESLogo = page.locator("//a[contains(@style,'ies')]");
    this.AWWALogo = page.locator("//a[contains(@style,'awwa')]");
    this.noResults = page.locator("//div[@class='search-no-results']");
    this.CGALogo = page.locator("//a[contains(@style,'CGA')]");
    this.clickOnLangDropDown = page.locator("//li[@id='language-menu']");
    this.languageContainer = page.locator("//div[@class='dropdown-menu dropdown-menu-right show']");
    this.Language = page.locator("//button[@class='dropdown-item']");
    this.StayOnPageBtn = page.locator("//div[contains(@data-bind,'displayTimer')]/a[contains(text(),'Stay')]");
    this.DefaultLanguage = page.locator("//li[@id='language-menu']//a[2]//div");
    this.magnifyingGlass = page.locator("//input[@placeholder='Search designation, keyword(s), title']/following-sibling::button");
    this.magnifyingGlassSub = page.locator("//button[@id='search_button_header']");
    this.username = page.locator("(//a[@class='d-flex align-items-center mobile-hide-style header-dropdown dropdown-toggle nav-link'])[4]");
    this.usernameOptions = page.locator("//div[@class='dropdown-menu dropdown-menu-end show']/a/span");
    this.Myaccount = page.locator("(//span[contains(text(),'My Account')])[2]");
    this.accountPage = page.locator("//div[@class='my-account-info']//span[contains(text(),'Name')]");
    this.OtherVersions = page.locator("//a[contains(text(),'Other Versions')]");
    this.myAccount = page.locator("//div[@class='dropdown-menu dropdown-menu-right show']");
    this.CompareVersions = page.locator("//span[contains(text(),'Compare Versions')]");
    this.checkbox2_CompareVersions = page.locator("(//div[@class='astm-custom-checkbox custom-control custom-checkbox checkbox-adjust']/input)[2]");
    this.compareButton = page.locator("//button[text()='Compare']");
    this.compareButton_Disabled = page.locator("//button[contains(@class,'astm-btn-disable')][text()='Compare']");
    this.compareVersionOptions = page.locator("//div[@data-testid='app-ribbon-menu']/div/div/div/button/div");
    this.changeListIcon = page.locator("//button[@data-testid='toggle-operation-list-panel-btn']");
    this.changeList = page.locator("//div[@id='virtual-list-content-container']");
    this.print = page.locator("//div[@class='print-html-compare-button']");
    this.closeComparisonButton = page.locator("//button[text()='Close Comparison']");
    this.recentlyUpdatedTab = page.locator("//span[contains(text(),'Recently Updated')]//ancestor::p");
    this.publisher = page.locator("//div[@class='card-content row']/div[1]//label/span[1]");
    this.myAccountHeader = page.locator("//h1[@class='astm-type-heading--h1 wlc-title my-account-header']");
    this.destinationNo = page.locator("//div[@class='card-content row']/div[1]//label/span[2]");
    this.document = page.locator("//div[@class='card-content row']/div[1]/div[1]/div[2]/span");
    this.status = page.locator("//div[@class='card-content row']/div[1]/div[1]/div[3]");
    this.lastUpdate = page.locator("//div[@class='card-content row']/div[1]/div[1]/div[4]");
    this.searchDropdown = page.locator("(//select[@id='types'])[2]");
    this.searchDropdownAll = page.locator("//select[@id='search_dropdown_mainpage']");
    this.searchDropdownAlltext = page.locator("//option[@value='ALL']");
    this.searchDropdownMySubscription = page.locator("//select[@class='select-search-select astm-type-body--lead']//option[contains(text(),'My Subscription')]");
    this.searchBox = page.locator("(//span[@class='span-container']//input)[2]");
    this.twitterLink = page.locator("//a[contains(@href,'twitter.com/ASTMIntl')]");
    this.facebookLink = page.locator("//a[contains(@href,'facebook.com/pages/ASTM')]");
    this.youtubeLink = page.locator("//a[contains(@href,'youtube.com/ASTMIntl')]");
    this.linkedinLink = page.locator("//a[contains(@href,'linkedin.com/company/astm')]");
    this.instagramLink = page.locator("//a[contains(@href,'instagram.com')]");
    this.astmRSSLink = page.locator("//a[contains(@href,'astm.org/RSS')]");
    this.Copyright_PermissionLink = page.locator("//a[contains(@href,'COPYRIGHT')]");
    this.helpDropdown = page.locator("(//div[text()='Help'])[2]");
    this.helpDropdown1 = page.locator("(//div[text()='Help'])[2]");
    this.supportFAQs = page.locator("#support");
    this.training = page.locator("#training");
    this.recentlyUpdatedCardContent = page.locator("//span[contains(text(),'A')]/ancestor::div[@class='card-adjust astm-card astm-card--raised astm-card--link astm-card card']");
    this.DocumentHeader = page.locator("//p[@class='astm-type-heading--h3 document-title']");
    this.Designation = page.locator("//p[@class='astm-type-heading--h6 astm-type-heading--h6-bold doc-designation']");
    this.DocStatus = page.locator("//span[@class='astm-type-body--small bold badge2 badge badge-secondary']");
    this.TrackDocument = page.locator("//span[contains(text(),'Track Document')]");
    this.trackIcon = page.locator("//span[contains(text(),'Untrack Document')]/preceding-sibling::*");
    this.favoriteIcon = page.locator("//span[contains(text(),'Remove Favorite')]/preceding-sibling::*");
    this.UntrackDocument = page.locator("//span[contains(text(),'Untrack Document')]");
    this.Downloadwithcompasspoints = page.locator("//span[contains(text(),'Download with Compass Points')]");
    this.AddToFavorites = page.locator("//span[contains(text(),'Add to Favorites')]");
    this.RemoveFavorites = page.locator("//span[contains(text(),'Remove Favorite')]");
    this.ToggleSwitches = page.locator("//div[@class='custom-control astm-custom-switch custom-switch']");
    this.Download = page.locator("//span[contains(text(),'Download')]");
    this.PDF = page.locator("//span[contains(text(),'PDF')]");
    this.trainingvideo = page.locator("//*[@id='Videos']/h5/b");
    this.pdfPages = page.locator("//div[@id='pageWidgetContainer1']");
    this.SearchFilter = page.locator("//*[@class='select-span-contianer custom-select-class']//child::select");
    this.HTMLActive = page.locator("//span[contains(text(),'HTML')]//ancestor::p");
    this.HTML = page.locator("//span[contains(text(),'HTML')]");
    this.trainingAndVideos = page.locator("//span[text()='Training & Videos']");
    this.eLearning = page.locator("//*[@id=\"eLearning\"]/h5");
    this.designation_HTML = page.locator("//h1[contains(text(),'Designation: ')]");
    this.organization_Caveat = page.locator("//p[@class='astm-type-body--small']");
this.ViewAllTracked = page.locator("//a[@class='astm-link']");
this.trackedDocument = page.locator("//*[@id='title-0']");
this.MenuHome = page.locator("//p[@class='astm-type-heading--h5 color-secondary major-side-menu']//a[@href='/']");
this.CustomCollections = page.locator("//a[@href='/custom-collections']");
this.SubscriptionUsage = page.locator("//*[@class=\"color-secondary sidebar-link\" and contains(text(),'Subscription Usage')]");
this.AENORlogo = page.locator("//a[@style='background-image: url(\"../../../../content/logos/aenor.svg\");']");
this.SubscriptionsMenu = page.locator("//p[@class='astm-type-heading--h5 color-secondary major-side-menu']//span[contains(text(),'Subscriptions')]");
this.TrackerMenu = page.locator("//p[@class='astm-type-heading--h5 color-secondary major-side-menu']//a[contains(@href,'trackChanges')]");
this.FavoritesMenu = page.locator("//p[@class='astm-type-heading--h5 color-secondary major-side-menu']//a[contains(@href,'favorites')]");
this.FavoritesHeader = page.locator("//span[contains(text(),'My Favorites')]");
this.NotesHeader = page.locator("//span[contains(text(),'My Notes')]");
this.notesFilter = page.locator("#notes_filter1");
this.clickOnNew = page.locator("//option[@value='NEW']");
this.notesDoc = page.locator("//td[@class='astm-table-td large-column astm-type-body--lead prevent-wrapping']");
this.clickOnMigrated = page.locator("//option[@value='MIGRATED']");
this.noMigratedNotes = page.locator("//span[@class='no-notes-title astm-type-heading--h5' and text()='No Migrated Notes']");
this.PoweredBy = page.locator("//span[@class='powerby astm-type-body']");
this.AWWAFooterLogo = page.locator("//div[@class='awwa-logo']");
this.CompareModalCheckbox = page.locator("//input[@type='checkbox' and @class='custom-control-input']");
this.DocumentHeading = page.locator("//p[@class='astm-type-heading--h6 astm-type-heading--h6-bold doc-designation']");
this.CompareButton = page.locator("//button[contains(text(),'Compare')]");
this.CloseCompareButton = page.locator("//i[@class='far fa-times']");
this.closeCompareModal = page.locator("//button[@class='btn btn-btn astm-btn btn-light model-btn-adjust']");
this.DownloadRedlinedButton = page.locator("//a[contains(text(),'Download Redlined PDF')]");
this.EditOpton = page.locator("//span[contains(text(),'Edit')]");
this.maskclass = page.locator("//div[@class='mask-cover']");
this.stdTrackerHeader = page.locator("//h1[contains(text(),'Track Changes with Standards Tracker')]");
this.searchText = page.locator("//input[@placeholder='Search designation, keyword(s), title']");
this.allSearch_RadioButton = page.locator("//input[@value='ALL']");
this.keyword_RadioButton = page.locator("//input[@value='K']");
this.designation_RadioButton = page.locator("//input[@value='D']");
this.mySubscription_RadioButton = page.locator("//input[@value='MYSUBSCRIPTION']");
this.resultsHeader = page.locator("//div[1]/div[1]/p");
this.searchFeedback = page.locator("//p/span[@data-testid = 'searchFeedbackLink-desktop']");
this.searchFeedback_popup = page.locator("//h5[text()= 'Search Feedback']");
this.searchedHeader = page.locator("//p[contains(text(), 'You searched for')]");
this.question1 = page.locator("//span[contains(text(), 'What document were you trying to find?')]");
this.feedback1 = page.locator("#documentSearching");
this.question2 = page.locator("//label[text()='Would you like to provide any other feedback related to your search?']");
this.additionalFeedback = page.locator("#additionalFeedback");
this.searchTextSub = page.locator("#search_input_header");
this.hyperLink = page.locator("//div[@id='pageSection11']//div[6]//span[1]");
this.hyperLink1 = page.locator("(//*[@class='link'])[5]");
this.hyperLink_HTML = page.locator("//a[@href='#sCustom3']");
this.confirm = page.locator("//button/span[text()='Confirm']");
this.replacedBy = page.locator("//span[text()='Replaced By:']/following-sibling::a");
this.contentBadge = page.locator("//div[1]/span[1]/span[3]");
this.serpFirstDocument = page.locator("(//div[@class='search-result']//a[@class='astm-link'])[1]");
this.pdfDefault = page.locator("//p[@data-testid='tabClick-tab active astm-type-heading--h6']/span/span[text()='PDF']");
this.versionFirstDocument = page.locator("(//a[text()='Versions'])[1]");
this.versionDropdown = page.locator("//div[@class='dropdown-menu show']");
this.languageFirstDocument = page.locator("(//a[text()='English'])[1]");
this.translatedLang = page.locator("(//span[text()='English'])[1]");
this.serpResults = page.locator("//div[@class='search-result']//a[@class='astm-link']/../preceding-sibling::span");
this.clickOnDocument = page.locator("//span[@class='astm-type-body--lead bold card-designation-no prevent-wrapping pointer-cursor']");
this.trackerCardContent = page.locator("//a[@class='block-with-text astm-type-body--lead blue-75 content block-with-text']");
this.menuTracker = page.locator("//div[@id='sidebar']//child::a[text()='Tracker']");
this.trackerRow = page.locator("//tr[@class='astm-table-tr']");
this.trackCheckBox = page.locator("//div[@class='custom-control astm-custom-switch custom-switch']//input[@type='checkbox']");
this.WhatStandard = page.locator("//b[contains(text(),'What')]");
this.AccountSelect = page.locator("//h1[contains(text(),'Select an Account')]");
this.subscriptionTab = page.locator("//div[contains(@class,'ipad-hide-style')]//span[text()='Subscriptions']");
this.accountDropdown = page.locator("(//a[@class='d-flex align-items-center mobile-hide-style header-dropdown dropdown-toggle nav-link'])[4]");
this.Signout = page.locator("//a[@id='account_menu_ipad_logout']");
this.HomepageTabs = page.locator("//select[@id='tab_filter']//option");
this.ViewAllFavorites = page.locator("//span[contains(text(),'VIEW ALL FAVORITES')]");
this.ViewAllTrackedDocs = page.locator("//span[contains(text(),'VIEW ALL TRACKED')]");
this.MyFavoritesHeader = page.locator("//div/div/h1/span");
this.favoriteDocument = page.locator("((//tr[@class='astm-table-tr'])[2]//td/a)[1]");
this.deleteFavoriteDocument = page.locator("((//tr[@class='astm-table-tr'])[2]//td/a)[2]");
this.delete_Popup = page.locator("//button[@type='button'][text()='Delete']");
this.myFavoritesDescription = page.locator("//p[@class='astm-type-body marginBottom20']");
this.noRecordsFound = page.locator("//*[@id='app-view-container']/div/div/div/p");
this.ViewAlltTracked = page.locator("//span[contains(text(),'VIEW ALL TRACKED')]");
this.NextPage = page.locator("//ul[@class='astm-pagination pagination']/descendant::a[@class='page-link']");
this.VersionDisclaimer = page.locator("//p[contains(text(),'This document is not an ASTM')]");
this.WTO = page.locator("//p[@class='astm-type-body--small']");
this.VideoTutorials = page.locator("//span[text()='Video Tutorials']");
this.VideoTutorialsLink = page.locator("//span[text()='Video Tutorials']");
this.VideosPageTitle = page.locator("//h1[contains(@class,'video-tutorials-title')]");
this.VideoTitle = page.locator("//div[@class='view-container']/descendant::div[contains(@class,'showborder')]/p[1]");
this.playVideo = page.locator("(//button[contains(@aria-label,'Play Video')])[2]");
this.pauseVideo = page.locator("(//button[contains(@aria-label,'Pause')])[2]");
this.videos = page.locator("//iframe[@class='document-iframe']");
this.WithdrawnLink = page.locator("//span[text()='Withdrawn']//ancestor::div[@class='search-result']//a[@class='astm-link']");
this.AENORPremiumLogo = page.locator("//div[@class='aenor-logo']");
this.DownloadPDF = page.locator("//span[@class='ipad-hide-style astm-type-body--lead']//span[text()='Download']");
this.PDFTronView = page.locator("(//div[@class='ribbons-container']//button[contains(text(),'View')])[1]");
this.AenorsearchBar = page.locator("//input[@id='search_input_header']");
this.AenorDocumentUNE139802 = page.locator("(//a[@class='astm-type-body'and text()='UNE 139802:2009'])[2]");
this.Download_PDFtab = page.locator("(//button[@class='Button ActionButton' ])[3]");
this.awwaDesign = page.locator("//a[contains(@href,'awwa')]");
this.CreateGroups = page.locator("//div[@id='editGroupModal']");
this.GroupName = page.locator("//label[contains(text(),'Group Name')]");
this.DeleteGroup = page.locator("//button[text()='Delete Group']");
this.Close = page.locator("//button[contains(text(),'Close')]");
this.update = page.locator("//button[contains(text(),'Update')]");
this.crossClose = page.locator("//button[@class='close']");
this.NavBarClose = page.locator("//p[@class='sidebar-close astm-type-body']");
this.Next = page.locator("//button[contains(text(),'Next')]");
this.TextunderDescription = page.locator("//span[@class='astm-type-body description-edit']");
this.Back = page.locator("//button[@class='btn btn-btn astm-btn btn-outline-secondary model-btn-adjust']");
this.CreateGroupIcon = page.locator("//button[@class='btn btn-btn astm-btn astm-btn--small btn-primary create-group']");
this.GroupNameTextBox = page.locator("[name='editGroupName']");
this.GroupDescriptionTextBox = page.locator("[name='editGroupDescription']");
this.AddGroupMember = page.locator("//p[@class='astm-type-body--lead step2']");
this.SearchBar_AddMember = page.locator("#search_input_compass_members");
this.MagnifyingGlass_AddMember = page.locator("(//*[@class='svg-inline--fa fa-search fa-w-16 search-icon'])[2]");
this.magnifyingGlass_EditMember = page.locator("#search_button_compass_members");
this.magnifyingGlass_Documents = page.locator("#search_button_compass_documents");
this.testingMigration = page.locator("//label[@class='custom-control-label']//span[contains(text(),'testingMigration')]");
this.RightArrow_AddMember = page.locator(" //i[@class='astm-icon far fa-arrow-circle-right']");
this.SelectAll_AddMember = page.locator("//a[@class='select-all astm-type-body--lead']");
this.IESQA_AddMember = page.locator("//label[@class='custom-control-label']//span[contains(text(),'IES101')]");
this.AenorSub_AddMember = page.locator("//label[@class='custom-control-label']//span[contains(text(),'Aenor101')]");
this.AWWAQA_AddMember = page.locator("//label[@class='custom-control-label'and text()='QA']");
this.rightSideMover = page.locator("//i[@class='astm-icon far fa-arrow-circle-right']");
this.groupMemberDocument = page.locator("//p[contains(text(),'Group Documents')]/../div/div/div/label");
this.compassMembersDocument = page.locator("//p[contains(text(),'Compass Documents')]/../div/div/div/label");
this.comprehensiveList = page.locator("//p[text()='A comprehensive list of citations to this standard are listed here.']");
this.Threedots_GroupTile = page.locator("//i[@class='astm-icon fas fa-ellipsis-v']");
this.Edit_GroupTile = page.locator("//div[@class='dropdown-menu show']/a[@class='Edit dropdown-item'and text()='Edit Group']");
this.SearchBar_AddDocument = page.locator("#search_input_compass_documents");
this.AddButton_AddDocWindow = page.locator("//button[text()='Add']");
this.CloseButton_AddDocWindow = page.locator("//button[text()='Close']");
this.Create = page.locator("//button[@class='btn btn-btn astm-btn btn-secondary model-btn-adjust']");
this.subscriptionsTabHomePage = page.locator("//div[contains(@class,'ipad-hide-style')]//span[text()='Subscriptions']");
this.subscriptionsTabASTMLink = page.locator("//p[@class='noPaddingMargin astm-type-body--lead bold' and text()='ASTM']");
this.editGroup = page.locator("../../div/a[text()='Edit Group']");
this.membersName = page.locator("//p[contains(text(),'Group Members')]/../div/div/div/label");
this.CopyrightText = page.locator("//p[@class='copy_right astm-type-body']");
this.tilesContainer = page.locator("//div[@class='card-adjust astm-card astm-card--raised astm-card--link groups-card card']");
this.groupSuccessUpdated = page.locator("//div[text()='Group successfully updated!']");
this.groupAddDocument = page.locator("//span[@class='add-documents action-button astm-type-heading--h5']");
this.emailTitle = page.locator("#emailGroupModal");
this.emailSubject = page.locator("//input[@placeholder='Enter your subject']");
this.emailMessage = page.locator("//textarea[@placeholder='Enter your message']");
this.deletePopUp = page.locator("//div[@class='astm-type-body--lead']");
this.emailCheckBox = page.locator("//label[@class='custom-control-label']");
this.deleteTitle = page.locator("//div[@id='deleteGroupModal']");
this.elementInput = page.locator("//label[@class='custom-control-label']/span");
this.ShareOption = page.locator("//a[@class='astm-type-body' and text()='Share']");
this.moreEmail = page.locator("(//div[@class='more dropdown']//a)[1]");
this.homeGroup = page.locator("//p[@class='astm-type-heading--h5 color-secondary major-side-menu']//a[text()='Home']");
this.SearchBar_Modal = page.locator("(//button[@class='search-btn astm-btn btn-primary' ])[2]");
this.GeneralDocuement = page.locator("(//p[@class='astm-type-heading--h5']/a[@class='astm-link'])[1]");
this.More = page.locator("//span[@class='ipad-hide-style astm-type-body--lead' ]/span[contains (text(),'More')]");
this.Magnifyglass_Modal = page.locator("//button[@class='search-btn astm-btn btn-primary']");
this.NoMatch = page.locator("//span[contains(text(),'Type a group name or valid email')]");
this.IlluminanceTables = page.locator("//a[@class='color-secondary sidebar-link' and text()='Illuminance Table']");
this.Elearning = page.locator("//span[@class='color-secondary sidebar-link' and text()='eLearning']");
this.NoAccess = page.locator("//div[@class='astm-type-body modal-body']");
this.NoAccess_api = page.locator("//div[@class='astm-type-body--lead modal-body']");
this.NoAccessElearning = page.locator("//div[@class='astm-type-body--lead modal-body']");
this.CloseNoAccess = page.locator("//button[@class='btn btn-btn astm-btn btn-light model-btn-adjust'and text()='Close']");
this.supplementalDocuments = page.locator("//b[text()='Supplemental Documents']");
this.RelatedLinks = page.locator("//span[@class='related-content-item-designation']");
this.content = page.locator("//div[@class='col-md-6 col-lg-4']//a");
this.AstmInternational = page.locator("//span[text()='ASTM International']");
this.modalEmailAddress = page.locator("//div[@class='share-search-content share-search-box col-12 col-sm-12 col-md-12 col-lg-12']//input");
this.magnifyingGlassEmailAddress = page.locator("//div[@class='share-search-content share-search-box col-12 col-sm-12 col-md-12 col-lg-12']//button");
this.EmailAddressCheck = page.locator("//p[@class='selected-group astm-type-body']//span");
this.seeMore = page.locator("//span[text()='See More']");
this.shareEmail = page.locator("//a[@title='Share']");
this.WorkItem = page.locator("//span[contains(text(),'Work Items')]");
this.Publisher_WorkItem = page.locator("//h5[@class='astm-type-heading--h5 astm-type-heading--h5-bold work-items-item']");
this.WorkItemNo = page.locator("//p[@class='astm-type-body--lead ballot-item-no']");
this.DateInitiated = page.locator("//p[@class='astm-type-body--lead work-item-date']");
this.StatusofWorkItem = page.locator("//p[@class='astm-type-body--lead ballot-item-status']//span[@class='astm-type-body--small badge']");
this.TechnicalContact = page.locator("//p[@class='astm-type-body--lead']");
this.dropdown = page.locator("(//a[@class='d-flex align-items-center mobile-hide-style header-dropdown dropdown-toggle nav-link']//div[@class='user_name astm-type-body mobile-hide-style' ])[4]");
this.docshareme = page.locator("(//span[contains(text(),'Documents Shared With Me')])[2]");
this.Mysharedoc = page.locator("//span[contains(text(),'My Shared Documents')]");
this.Mydoc = page.locator("//table[@class='table table-striped astm-table table table-hover']//ancestor::div[@class='shared-standards-content container']//h1");
this.designation = page.locator("//span[@class='bold']");
this.pagination = page.locator("//ul[@class='astm-pagination pagination']");
this.nextpagination = page.locator("//a[@class='page-link hide-mobile' and text()='Next']");
this.chevron_WI = page.locator("//span[@class='chevron']//*[@class='svg-inline--fa fa-chevron-down fa-w-14 ']");
this.TC_MWI = page.locator("//p[@class='astm-type-body--lead collapse-text']");
this.PubWI = page.locator("//h5[@class='astm-type-heading--h5 astm-type-heading--h5-bold work-items-item']//ancestor::div[@class='contentContainer row']//a");
this.chevronup = page.locator("//span[@class='chevron']//*[@class='svg-inline--fa fa-chevron-up fa-w-14 ']");
this.WIModaltitle = page.locator("//div[@class='modal-title']");
this.WIModalbody = page.locator("//div[@class='astm-type-body--lead modal-body']");
this.Help = page.locator("(//div[@class='user_name astm-type-body mobile-hide-style' and text()='Help'])[2]");
this.moreResource = page.locator("//span[@class='dropdown-item-link astm-type-body' ]//span[text()='More Resources']");
this.docShareWithMe = page.locator("//span[text()='Documents Shared With Me']//parent::span[@class='dropdown-item-link astm-type-body']//parent::a[@id='account_menu_ipad_shared-with-me']");
this.UserResourcePage = page.locator("//h1[@class='astm-type-heading--h5 astm-type-heading--h5-bold user-resources-title' ]");
this.leftNavigationLink = page.locator("//div[@class='user-resources-sections']//a");
this.LTSLink = page.locator("//div[@id='Library Technology and Services']//div");
this.LTS = page.locator("//a[@class='astm-type-body sections-title-color' and text()='Library Technology and Services']");
this.CaratLTS = page.locator("//label[@class='pl-0 pointer-cursor astm-type-body--small tree-chevron']");
this.LTSdetails = page.locator("//p[@class='astm-type-body--lead option']");
this.DocumentC = page.locator("//a[@class='astm-type-body']//span[@class='bold']");
this.DesignationC = page.locator("//a[@class='astm-type-body']//span[@class='bold']");
this.TitleC = page.locator("//a[@class='astm-type-body']//span[@class='bold']");
this.DocTable = page.locator("//tr[@class='astm-table-tr']//th");
this.firstLast = page.locator("(//a[@class='astm-type-body'])[2]");
this.PDFnoNotes = page.locator("//span[@class='no-notes-content astm-type-body--lead']");
this.Welcometitle = page.locator("//h1[@class='astm-type-heading--h5 astm-type-heading--h5-bold wlc-title wlc-title-margin']");
this.Accountid = page.locator("(//div[@class='user_name astm-type-body mobile-hide-style'])[8]");
this.DocType = page.locator("//span[@class='astm-type-body--small bold badge1 badge badge-secondary']");
this.MARCrecords = page.locator("//p[@class='astm-type-body--lead bold option' and text()='MARC Records']");
this.clickOnMARCrecords = page.locator("//p[@class='astm-type-body--lead bold option' and text()='MARC Records']//following-sibling::label");
this.listOfJournals = page.locator("//p[@class='astm-type-body--lead option']");
this.DeleteIcon = page.locator("//i[@class='far fa-trash-alt']");
this.Delete = page.locator("//*[contains(text(),'Delete')]");
this.PDFdownloadArrow = page.locator("//i[@class='far fa-arrow-to-bottom']");
this.DownloadRedlinedArrow = page.locator("//i[@class='far fa-arrow-to-bottom']");
this.DeleteIcon_AWWA_Tracker = page.locator("(//i[@class='astm-icon far fa-trash-alt'])[11]");
this.SABADoc = page.locator("//a[@class='itemname trq-text-primary trq-mb-0 trq-mt-0']");
this.DownloadOption = page.locator("//i[@class='far fa-arrow-to-bottom']");
this.ZipDownloadOption = page.locator("//i[@class='far fa-arrow-to-bottom']");
this.ZipDownloadOption_api = page.locator("(//i[@class='far fa-arrow-to-bottom'])[2]");
this.langDropDownDoc = page.locator("(//div[@class='dropdown']//a[@class='nav-link update-time astm-type-heading--h6 gary-30 dropdown-toggle'])[1]");
this.langClick = page.locator("//div[@class='dropdown-menu show']//a[@class='dropdown-item']");
this.UserGuideLink = page.locator("//span[contains(text(),'User Guide')]");
this.HomeLink = page.locator("//a[@class='astm-type-body' and text()='Home']");
this.HomeLogo = page.locator("//a[@class='user-logo']");
this.ResultTypeDropdown = page.locator("//label[@class='pl-0 pointer-cursor astm-type-body--small tree-chevron']");
this.DocumentDropdown = page.locator("//label[@id='content_type--DigitalLibrary-top']");
this.Proceeding_ResultType = page.locator("//div[@class='prevent-wrapping-2line label-span' and text()='Proceeding']");
this.CategoryLinks = page.locator("//div[@class='tree-node astm-custom-checkbox custom-control custom-checkbox']");
this.SecondaryListDropdown_Category = page.locator("//label[@id='taxo_terminfo_scopeid-APP-00-00-00-00-00-top']");
this.SecondaryList_Category = page.locator("//div[@class='collapse show']//div[@class='prevent-wrapping-2line label-span']");
this.Active_Refinment = page.locator("//div[@class='prevent-wrapping-2line label-span' and text()='Active']");
this.ActiveDocuments = page.locator("//span[@class='astm-type-body--small bold badge2 badge badge-secondary']");
this.DocumentDesignation = page.locator("//span[@class='astm-type-body--lead bold card-designation-no prevent-wrapping pointer-cursor']");
this.CGADocumentDropdown = page.locator("//label[@id='asset_status--DigitalLibrary-top']");
this.Withdrawn_Refinment = page.locator("//div[@class='prevent-wrapping-2line label-span' and text()='Withdrawn']");
this.WithdrawnDocuments = page.locator("//span[@class='astm-type-body--small bold badge5 badge badge-secondary']");
this.CGADocumentRefinment = page.locator("//div[@class='prevent-wrapping-2line label-span' and text()='Documents']");
this.documentTypeVideo = page.locator("//label[@id='DigitalLibrary-top']");
this.standardVideo = page.locator("//label[@id='asset_type-Standard-DigitalLibrary-top']");
this.videosOnSerp = page.locator("//div[text()='Videos']");
this.ExplorationAndProduction = page.locator("//p[text()='Exploration and Production']");
this.SecondaryList = page.locator("//div[@class='col-md-6']");
this.TranslationDropdown = page.locator("//a[@class='nav-link astm-type-body gary-30 dropdownToggle dropdown-toggle']");
this.OtherVersionDropdown = page.locator("nav-link astm-type-body gary-30 dropdownToggle dropdown-toggle");
this.OtherVersionList = page.locator("//div[@class='dropdown-menu show']//a[@class='dropdown-item']");
this.TranslatedStandard = page.locator("//span[@class='astm-type-body--small bold badge1 badge badge-secondary']");
this.SwitchAccountInHeader = page.locator("//span[text()='Switch Account']//parent::a[@id='account_menu_ipad_switch-account']");
this.selectAccount = page.locator("//h1[@class='astm-type-heading--h1 account-sub-title' and text()='Select an Account']");
this.ButtonOnSelectAccountScreen = page.locator("//button[@class='btn astm-btn btn-secondary']");
this.WelcomeBackAfteraccountSelection = page.locator("//h1[@class='astm-type-heading--h5 astm-type-heading--h5-bold wlc-title wlc-title-margin']");
this.signOut = page.locator("//span[text()='Sign Out']//parent::a[@id='account_menu_ipad_logout']");
this.CompareVersionTileMessage = page.locator("//p[contains(text(),'Easily compare the differences between active and historical standards in PDF format.')]");
this.CGAAddresse = page.locator("//p[contains(text(),'Compressed Gas Association, 8484 Westpark Drive, Suite 220, McLean, VA 22102')]");
this.APIErrorMessage = page.locator("//h2[contains(text(),'404 - Resource Not Found, please contact support.')]");
this.listUnderSearchBox = page.locator("//div[@class='search-suggestion-container']//p[@class='astm-type-body content']//a");
this.TechnicalReportRefinment = page.locator("//div[@class='prevent-wrapping-2line label-span' and text()='Technical Report']");
this.LightingLibraryContentsLink = page.locator("//a[text()='Lighting Library Contents']");
this.ReferenceRetriever = page.locator("//a[@class='color-secondary sidebar-link'and text()='Reference Retriever']");
this.hpdf = page.locator("(//span[@class='link'])[5]");
this.trackerDocuments = page.locator("//tbody[@class='mobile-hide-style']//tr[@class='astm-table-tr']//td[1]//a[@class='astm-type-body']");
this.favoritesDocument = page.locator("//tr[@class='astm-table-tr']//td//a[@class='astm-type-body']");
this.annotate = page.locator("//button[@class='ribbon-group' and text()='Annotate']");
this.annotateActive = page.locator("//button[@class='ribbon-group active' and text()='Annotate']");
this.viewNotes = page.locator("//button[@class='Button ActionButton' and @aria-label='View Notes']");
this.commentsBox = page.locator("//button[@class='Button active hide-in-small-mobile']");
this.notesInDocuments = page.locator("//div[@class='Note']");
this.notesPopUp = page.locator("//div[@class='NotePopup']");
this.EditInNotes = page.locator("//div[@class='option' and text()='Edit']");
this.EditModal = page.locator("//div[@id='addCommentsModal']");
this.existingNotes = page.locator("//span[@class='contents']");
this.SaveNotesButton = page.locator("//button[text()='Save']");
this.textAreaNotesModal = page.locator("//textarea[@id='comments']");
this.RIS = page.locator("//span[@class='download-irs']");
this.SelectedTechnicalPapers = page.locator("//p[contains(text(),'Selected Technical Papers')]");
this.Export_Button = page.locator("//button[contains(text(),'Export')]");
this.CitationInfoIcon = page.locator("//i[@class='astm-icon far fa-info-circle']");
this.MyAccounts = page.locator("//a[@id='account_menu_ipad_my-account_profile']");
this.firstNameLabel_PersonalInfoPage = page.locator("//div[@class='font-weight-bold form-label' and contains(text(),'First Name')]");
this.middleNameLabel_PersonalInfoPage = page.locator("//div[@class='font-weight-bold form-label' and contains(text(),'Middle Name')]");
this.lastNameLabel_PersonalInfoPage = page.locator("//div[@class='font-weight-bold form-label' and contains(text(),'Last Name')]");
this.emailLabel_PersonalInfoPage = page.locator("//div[@class='font-weight-bold form-label' and contains(text(),'Email')]");
this.compassEditBtn_PersonalInfoPage = page.locator("//button[@id='compass-view-edit-btn']");
this.compassLink_PersonalInfoPage = page.locator("//a[text()='Compass']");
this.OrganisationCompass = page.locator("//select[@class='custom-select astm-custom-select form-control']");
this.QAOrganisationCompass = page.locator("//select[@class='custom-select astm-custom-select form-control']//option[contains(text(),'SUB IES Account QA')]");
this.OtherVersionList = page.locator("//div[@class='dropdown-menu show']//a[@class='dropdown-item']");
    this.TranslatedStandard = page.locator("//span[@class='astm-type-body--small bold badge1 badge badge-secondary']");
    this.SwitchAccountInHeader = page.locator("//span[text()='Switch Account']//parent::a[@id='account_menu_ipad_switch-account']");
    this.selectAccount = page.locator("//h1[@class='astm-type-heading--h1 account-sub-title' and text()='Select an Account']");
    this.ButtonOnSelectAccountScreen = page.locator("//button[@class='btn astm-btn btn-secondary']");
    this.WelcomeBackAfteraccountSelection = page.locator("//h1[@class='astm-type-heading--h5 astm-type-heading--h5-bold wlc-title wlc-title-margin']");
    this.signOut = page.locator("//span[text()='Sign Out']//parent::a[@id='account_menu_ipad_logout']");
    this.CompareVersionTileMessage = page.locator("//p[contains(text(),'Easily compare the differences between active and historical standards in PDF format.')]");
    this.CGAAddresse = page.locator("//p[contains(text(),'Compressed Gas Association, 8484 Westpark Drive, Suite 220, McLean, VA 22102')]");
    this.APIErrorMessage = page.locator("//h2[contains(text(),'404 - Resource Not Found, please contact support.')]");
    this.listUnderSearchBox = page.locator("//div[@class='search-suggestion-container']//p[@class='astm-type-body content']//a");
    this.TechnicalReportRefinment = page.locator("//div[@class='prevent-wrapping-2line label-span' and text()='Technical Report']");
    this.LightingLibraryContentsLink = page.locator("//a[text()='Lighting Library Contents']");
    this.ReferenceRetriever = page.locator("//a[@class='color-secondary sidebar-link'and text()='Reference Retriever']");
    this.hpdf = page.locator("(//span[@class='link'])[5]");
    this.trackerDocuments = page.locator("//tbody[@class='mobile-hide-style']//tr[@class='astm-table-tr']//td[1]//a[@class='astm-type-body']");
    this.favoritesDocument = page.locator("//tr[@class='astm-table-tr']//td//a[@class='astm-type-body']");
    this.annotate = page.locator("//button[@class='ribbon-group' and text()='Annotate']");
    this.annotateActive = page.locator("//button[@class='ribbon-group active' and text()='Annotate']");
    this.OrganisationCompass = page.locator("//select[@class='custom-select astm-custom-select form-control']");
    this.QAOrganisationCompass = page.locator("//select[@class='custom-select astm-custom-select form-control']//option[contains(text(),'SUB IES Account QA')]");
    this.OrganisationCompassIES = page.locator("//select[@class='custom-select astm-custom-select form-control']//option[contains(text(),'Malcar Northwest')]");
    this.OrganisationCompassSelect = page.locator("//select[@class='custom-select astm-custom-select form-control']//option[contains(text(),'CGA Test Account')]");
    this.OrganisationCompassSelectCGA = page.locator("//select[@class='custom-select astm-custom-select form-control']//option[contains(text(),'POC Gas and Air')]");
    this.OrganisationCompassSelectAWWA = page.locator("//select[@class='custom-select astm-custom-select form-control']//option[contains(text(),'City of Guelph')]");
    this.OrganisationCompassSelectAPI = page.locator("//select[@class='custom-select astm-custom-select form-control']//option[contains(text(),'TJ Machine Tool LTD')]");
    this.OrganisationCompassSelectAenor = page.locator("//select[@class='custom-select astm-custom-select form-control']//option[contains(text(),'AENOR')]");
    this.PersonalInformation = page.locator("//a[@class='active nav-link' and contains(text(),'Personal Information')]");
    this.OrgCompass = page.locator("//label[@class='font-weight-bold form-label d-block']");
    this.orgDropdown_compassLink = page.locator("#organizations");
    this.AccountCompass = page.locator("//a[@id='compass-tab' and text()='Compass']");
    this.cancelBtn_additionalOrganization = page.locator("//button[text()='Cancel']");
    this.saveBtn_additionalOrganization = page.locator("//button[text()='Save']");
    this.accountNumberLabelCompassLink = page.locator("//div[@class='font-weight-bold form-label' and text()='Account #: ']");
    this.additionalOrgLbl_CompassLink = page.locator("//div[text()='Additional Organization(s): ']");
    this.additionalOrganisationTextField_CompassLink = page.locator("#additionalOrganization");
    this.addOrgVal_CompassLink = page.locator("//div[text()='Additional Organization(s): ']/following-sibling::div");
    this.editLinkUnderCompassLabel = page.locator("//button[@id='compass-view-edit-btn']");
    this.accountNoValueUnderCompassLink = page.locator("//div[text()='Account #: ']/following-sibling::div");
    this.passwordLink_ProfilePage = page.locator("#password-tab");
    this.resetPwdSuccessMsg_ProfilePage = page.locator("//span[text()='Password Reset Successful']");
    this.resetPwdSuccessMsgCloseBtn_ProfilePage = page.locator("//button[@type='button' and @class='close']");
    this.footerSectionHomeLink = page.locator("//ul[@class='contact_us']//a[text()='Home']");
    this.footerSectionContactLink = page.locator("//ul[@class='contact_us']//a[text()='Contact']");
    this.contactLinkContactPageNotFoundMsg = page.locator("//h1[text()='Your request cannot be processed']");
    this.contactLinkContactPageNotFoundMsg_APITenant = page.locator("//h1[text()='The page you requested was not found.']");
    this.footerLinks = page.locator("//ul[@class='contact_us']//a");
    this.addressOfAPIFromFooterSection = page.locator("//p[contains(@class,'copy_right')][1]");
    this.addressOfAENORFromFooterSection = page.locator("//p[contains(@class,'copy_right')][1]");
    this.copyrightYearWithASTMAddressFromFooterSection = page.locator("//p[contains(@class,'copy_right')][2]");
    this.copyrightYearWithASTMAddressFromFooterSection_ASTMTenant = page.locator("//p[contains(@class,'copy_right')]");
    this.closeBtn_invalidPwdErrMsg = page.locator("//button[@class='close']");
    this.newPasswordInputField_PasswordLink = page.locator("#newPassword");
    this.confirmPassword_PasswordLink = page.locator("#confirmPassword");
    this.savePasswordBtn_PasswordLink = page.locator("//button[@type='submit' and text()='Save Password']");
    this.passwordHeader_UnderPasswordLink = page.locator("//h2[text()='Password']");
    this.currentPasswordInputField_PasswordLink = page.locator("#oldPassword");
    this.currentPasswordInvalidErrorMsg_PasswordLink = page.locator("//img[@alt='error-icon']/following-sibling::span");
    this.StageOrganisationCompass = page.locator("//select[@class='custom-select astm-custom-select form-control']//option[contains(text(),'Oklahoma DOT')]");
    this.inputCompare = page.locator("(//input[@class='custom-control-input'])[2]");
    this.MenuSubscription = page.locator("//span[@class='color-secondary sidebar-link' and contains(text(),'Subscriptions')]");
    this.MenuASTM = page.locator("//a[@class='sidebar-link color-secondary' and contains(text(),'ASTM')]");
    this.closeNavBar = page.locator("//p[text()='Close']");
    this.DocumentDetails = page.locator("//span[@class='astm-type-heading--h6 blue-70 pointer-cursor']");
    this.cookieCloseButton = page.locator("//button[@class='onetrust-close-btn-handler onetrust-close-btn-ui banner-close-button ot-close-icon']");
    this.buttonSelect = page.locator("//a[@class='btn astm-btn btn-secondary account-select-button']");
    this.agreeAndContinue = page.locator("//button[text()='Agree and Continue']");
    this.SignInNew = page.locator("(//span[text()='Sign In/Register'])[2]");
    this.VideoTutorialLink = page.locator("//span[contains(text(),'Video Tutorials')]");
    this.ViewUserVisibility = page.locator("//h5[@class='modal-title']");
    this.AddUserMAE = page.locator("//button[@class='btn btn-warning add-user']");
    this.TestAutomationGroup = page.locator("//a[contains(text(),'Test case for automation') ]");
    this.AddDocuments = page.locator("//span[@class='add-documents action-button astm-type-heading--h5']");
    this.GroupAddDocument = page.locator("//div[@class='astm-custom-checkbox custom-control custom-checkbox']");
    this.Add = page.locator("//button[contains(text(),'Add')]");
    this.AddDocumentSearchBar = page.locator("(//input[@class='search-input astm-type-body--lead'])[2]");
    this.Trash = page.locator("(//i[@class='astm-icon far fa-trash-alt'])[2]");
    this.IECTestAutomationGroup = page.locator("//a[contains(text(),'Test case for automation') ]");
    this.RightSideDocument = page.locator("//label[@class='custom-control-label']");
    this.SSOUsername = page.locator("//input[@id='UserName']");
    this.SSOPassword = page.locator("//input[@id='Password']");
    this.SSOSignIN = page.locator("//input[@class='loginbtn btn btn-primary btn-lg']");
    this.UserGuideLinkEnglish = page.locator("//a[@id='user_guide_en']");
    this.UserGuideLinkSpanish = page.locator("//a[@id='user_guide_es_la']");
    this.Contact = page.locator("//a[@class='astm-type-body' and contains(text(),'Contact')]");
    this.PrivacyPolicyFooter = page.locator("//a[@class='astm-type-body' and contains(text(),'Privacy Policy')]");
    this.PoliciesFooter = page.locator("//a[@class='astm-type-body' and contains(text(),'Policies')]");
    this.Copyright_Permissions = page.locator("//a[@class='astm-type-body' and contains(text(),'Copyright/Permissions')]");
    this.CustomCollectionsHeader = page.locator("//span[contains(text(),'Custom Collection')]");
    this.customCollectionsLinks = page.locator("//tr[@class='astm-table-tr']//a[@class='astm-type-body']");
    this.documentStatus = page.locator("//span[@class='badge-span']/span[@class='astm-type-body--small bold badge2 badge badge-secondary']");
    this.documentDesignation = page.locator("//p[@class='astm-type-heading--h3 document-title']");
    this.designation_doc = page.locator("(//div/div/div[3]/p[1])[2]");
    this.publisherDropdown = page.locator("//select[@id='custom-collections_filter1']");
    this.WohlersReportRecentlyAccessed = page.locator("//div[@class='card-body']//p[contains(text(),'Wohlers Report')]");
    this.AddShareEmail = page.locator("//div[@class='share-search-content share-search-box col-12 col-sm-12 col-md-12 col-lg-12']//input");
    this.SearchEMail = page.locator("(//button[@class='search-btn astm-btn btn-primary'])[2]");
    this.AddEmail = page.locator("//button[text()='add']");
    this.ShareEmail = page.locator("//button[text()='Share']");
    this.TechnicalCommittees = page.locator("//h1[text()='Technical Committees']");
    this.Membership = page.locator("//h1[text()='Membership']");
    this.favoritesDocLinks = page.locator("//table[contains(@class,'table-striped')]/tbody/tr/td[1]/a");
    this.deleteFavConfirm = page.locator("//button[contains(@class,'btn-danger')]");
    this.TrackedDocLinks = page.locator("//table[contains(@class,'table-striped')]/tbody/tr/td[1]/a");
    this.VersionDDItems = page.locator("//div[@class='dropdown show']/div/a");
    this.VersionDDLink = page.locator("//a[contains(text(),'Versions')]");
    this.MyAccount = page.locator("//li[@id='account_menu_ipad']/descendant::a[3]");
    this.emailinMyAccountPage = page.locator("//div[contains(text(),'Email')]/following-sibling::div");
    this.switchAcc = page.locator("//li[@id='account_menu_ipad']/descendant::a[4]");
    this.switchAccHeading = page.locator("//h1[contains(text(),'Select an Account')]");
    this.docsShared = page.locator("//li[@id='account_menu_ipad']/descendant::a[5]");
    this.nodocsharemsg = page.locator("//div[@class='shared-standards-block']/p");
    this.sharedDocrows = page.locator("//table[contains(@class,'table-striped')]/tbody/tr");
    this.NavMenuLinks = page.locator("//div[@class='side show-sidebar']/descendant::a");
    this.HeaderLinksDD = page.locator("//div[@class='document-activity']/span/span");
    this.CitationModelHeader = page.locator("//h5[@class='modal-title']/p");
    this.Pdfsearch = page.locator("//button[@data-element='selectToolButton']/following-sibling::div/following-sibling::button[1]");
    this.HTMLCompateDisclaimer = page.locator("//div[@class='astm-type-body']/p");
    this.NavMenuTrackerLink = page.locator("//a[contains(text(),'Tracker')]");
    
}

         }
    