import { Page, Locator, expect,test } from '@playwright/test';
import { stepLogger } from '../utils/logger';
import { attachScreenshot } from '../utils/reportUtils';

export class LoginSubscriptionpage {
  //readonly page: Page;
  readonly userName: Locator;
  readonly userNameNew: Locator;
  readonly passwordNew: Locator;
  readonly password: Locator;
  readonly header: Locator;
  readonly validLogin: Locator;
  readonly loginButton: Locator;
  readonly LCAmodal: Locator;
  readonly SignInNew: Locator;
  readonly signInOrRegister: Locator;
  readonly SignInHidden: Locator;
  readonly inValidLoginMessageHeader: Locator;
  readonly AccountSelect: Locator;
  readonly AccountSelectButton: Locator;
  readonly Agree: Locator;
  readonly Cookie: Locator;
  readonly AgreeCookie: Locator;
  readonly RemoveCookie: Locator;
  readonly AuthenticationVerification: Locator;
  readonly JWTToken: Locator;
  readonly spinner: Locator;
  readonly unauthorized_popUp: Locator;
  readonly unauthorizedMsg_popUp: Locator;
  readonly UnexpectedErrorBanner: Locator;
  readonly spinnerLoading: Locator;
  readonly usernameFedSSO: Locator;
  readonly passwordFedSSO: Locator;
  readonly SignInFedSSO: Locator;
  readonly OCLClogo: Locator;
  readonly ezproxyUser: Locator;
  readonly ezproxyPassword: Locator;
  readonly ezproxyLogin: Locator;
  readonly OktaSignUpBtn: Locator;
  readonly OKTAHeader: Locator;
  readonly CreateAccountHeader: Locator;
  readonly InputEmail: Locator;
  readonly InputPassword: Locator;
  readonly RegisterBtn: Locator;
  readonly ProfileInformationHeader: Locator;
  readonly InputFirstName: Locator;
  readonly InputLastName: Locator;
  readonly SaveBtn: Locator;
  readonly AccessToCompassModelHeader: Locator;
  readonly OkBtn: Locator;
  readonly RegisterHeaderTab: Locator;
  readonly Registerlink: Locator;
  readonly Academicaccess: Locator;
  readonly Reg_Firstname: Locator;
  readonly Reg_Lastname: Locator;
  readonly Reg_Email: Locator;
  readonly Reg_Password: Locator;
  readonly Invalid_Reg_Password: Locator;
  readonly Reg_ConfirmPassword: Locator;
  readonly Invalid_Reg_ConfirmPassword: Locator;
  readonly CreateAccountBtn: Locator;
  readonly Signin: Locator;
  readonly SuccessMsg: Locator;
  readonly RegistrationSuccessMsg: Locator;
  readonly Compass_Username: Locator;
  readonly Compass_Password: Locator;
  readonly Compass_SignIn: Locator;
  readonly cookieAcceptBtn: Locator;
  readonly agreeAndContinue: Locator;
  readonly cookieRejectBtn: Locator;
  readonly CompassLogo: Locator;
  readonly PublicStandardProductsTitle: Locator;
  readonly StayOnPageBtn: Locator;
  readonly CompassProductTitle: Locator;
  readonly GoToASTMcompassBtn: Locator;
  readonly ASTMLicenseHeader: Locator;
  readonly MenuBar: Locator;
  readonly sideBarOptions: Locator;
  readonly compassPointNameLink: Locator;
  readonly compassPointHeader: Locator;
   readonly docPageCompasspointListLink: Locator;
  readonly ASTMlogo: Locator;
  readonly rememberMeCheckbox: Locator;
  readonly compassApplicationSelect: Locator;
  readonly Compass_SignInButton: Locator;
  readonly sharedDoc: Locator;
  readonly emailIcon: Locator;
  readonly CompassDropdown: Locator;
  readonly DropdownPMPage: Locator;
  readonly MyAccount: Locator;
  readonly SinoutPMPage: Locator;
  readonly SelectAenorAccount: Locator;
  readonly ApiDropdown: Locator;
  readonly UsernameDropDown: Locator;
  readonly UsernameDropDown_SignOut: Locator;
  readonly CompassHomePage_SelectButton: Locator;



  constructor(page: Page) {
    this.userName = page.locator("[name='username']");
    this.userNameNew = page.locator("[name='userName']");
    this.passwordNew = page.locator("[name='encPass']");
    this.password = page.locator("#encPass");
    this.header = page.locator("[name='header']");
    this.validLogin = page.locator("//h1[contains(text(),'Welcome Back')]");
    this.loginButton = page.locator("//button[text()='Sign In']");
    this.LCAmodal = page.locator("//div[@class='modal-content']//div[@class='modal-header']");
    this.SignInNew = page.locator("(//span[text()='Sign In/Register'])[2]/parent::div");
    this.signInOrRegister = page.locator("(//span[text()='Sign In/Register']/parent::div[contains(@class,'user-sign-in')])[2]");
    this.SignInHidden = page.locator("//div[@aria-hidden='false']//a[@id='account_menu_ipad_login-item']");
    this.inValidLoginMessageHeader = page.locator("//span[contains(text(),'Username or password is incorrect, please try again')]");
    this.AccountSelect = page.locator("//h1[contains(text(),'Select an Account')]");
    this.AccountSelectButton = page.locator("//button[@class='btn astm-btn btn-secondary']");
    this.Agree = page.locator("//button[@class='btn astm-btn btn-secondary astm-type-body--lead']");
    this.Cookie = page.locator("#onetrust-group-container");
    this.AgreeCookie = page.locator("#onetrust-accept-btn-handler");
    this.RemoveCookie = page.locator("#onetrust-reject-all-handler");
    this.AuthenticationVerification = page.locator("//h1[@class='astm-type-heading--h2 auth-verified-title']");
    this.JWTToken = page.locator("body");
    this.spinner = page.locator("//*[contains(@class, 'spinner-icon') and contains(@class, 'spinner-border')]");
    this.unauthorized_popUp = page.locator("//div[text()='Access to Compass']");
    this.unauthorizedMsg_popUp = page.locator("/html/body/div[3]/div/div[1]/div/div/div[2]/div");
    this.UnexpectedErrorBanner = page.locator("//h2[text()='An unexpected error has occurred.']");
    this.spinnerLoading = page.locator(".spinner-border.spinner-loading");
    this.usernameFedSSO = page.locator("#okta-signin-username");
    this.passwordFedSSO = page.locator("#okta-signin-password");
    this.SignInFedSSO = page.locator("#okta-signin-submit");
    this.OCLClogo = page.locator("//img[@src='/public/logo.png']");
    this.ezproxyUser = page.locator("[name='user']");
    this.ezproxyPassword = page.locator("[name='pass']");
    this.ezproxyLogin = page.locator("//input[@type='submit']");
    this.OktaSignUpBtn = page.locator("//a[@class='registration-link']");
    this.OKTAHeader = page.locator("//h1/img");
    this.CreateAccountHeader = page.locator("//h2");
    this.InputEmail = page.locator("//input[@name='email']");
    this.InputPassword = page.locator("//input[@name='password']");
    this.RegisterBtn = page.locator("//input[@type='submit']");
    this.ProfileInformationHeader = page.locator("//h2[text()='Profile Information']");
    this.InputFirstName = page.locator("#firstName");
    this.InputLastName = page.locator("#lastName");
    this.SaveBtn = page.locator("//button[text()='Save']");
    this.AccessToCompassModelHeader = page.locator("//h5");
    this.OkBtn = page.locator("//button[text()='OK']");
    this.RegisterHeaderTab = page.locator("(//div[contains(@class,'sign-in')])[2]");
    this.Registerlink = page.locator("//a[text()='Register']");
    this.Academicaccess = page.locator("//select[@name='academicAccess']");
    this.Reg_Firstname = page.locator("#firstName");
    this.Reg_Lastname = page.locator("#lastName");
    this.Reg_Email = page.locator("//input[@name='email']");
    this.Reg_Password = page.locator("#password");
    this.Invalid_Reg_Password = page.locator("//input[contains(@class, 'invalid') and @id='password']");
    this.Reg_ConfirmPassword = page.locator("#confirmPassword");
    this.Invalid_Reg_ConfirmPassword = page.locator("//input[contains(@class, 'invalid') and @id='confirmPassword']");
    this.CreateAccountBtn = page.locator("//button[text()='Create Account']");
    this.Signin = page.locator("//button[text()='Sign In']");
    this.SuccessMsg = page.locator("//div[@class='astm-alert-text']");
    this.RegistrationSuccessMsg = page.locator("//span[contains(text(),'Registration Successful')]");
    this.Compass_Username = page.locator("#userName");
    this.Compass_Password = page.locator("#encPass");
    this.Compass_SignIn = page.locator("//button[text()='Sign In']");
    this.cookieAcceptBtn = page.locator("#onetrust-accept-btn-handler");
    this.agreeAndContinue = page.locator("//button[text()='Agree and Continue']");
    this.cookieRejectBtn = page.locator("#onetrust-accept-btn-handler");
    this.CompassLogo = page.locator("//a[@class='user-logo']");
    this.PublicStandardProductsTitle = page.locator("//span[@class='astm-type-body--lead title-text-bold']/b");
    this.StayOnPageBtn = page.locator("//a[text()='Stay on Page']");
    this.CompassProductTitle = page.locator("//p[contains(@class,'doc-designation')]");
    this.GoToASTMcompassBtn = page.locator("//a[contains(text(),'Go to ASTM Compass')]");
    this.ASTMLicenseHeader = page.locator("//div[@id='exampleModalLabel']");
    this.MenuBar = page.locator("//a[@class='brand-logo']/label/span");
    this.sideBarOptions = page.locator("//div[@id='sidebar']/div/p/a");
    this.compassPointNameLink = page.locator("//tr[@class='astm-table-tr']/td/span/a");
    this.compassPointHeader = page.locator("//h2[text()='My Compass Points']");
     this.docPageCompasspointListLink = page.locator("//span[text()='Compass Points List']");
    this.ASTMlogo = page.locator("body > div.login-container.login-astm > div > div > img");
    this.rememberMeCheckbox = page.locator("#rememberMe");
    this.compassApplicationSelect = page.locator("//input[@value='Compass']/following-sibling::button");
    this.Compass_SignInButton = page.locator("#header-tabs .user-sign-in");
    this.sharedDoc = page.locator("(//tr[@class='astm-table-tr'])[2]");
    this.emailIcon = page.locator("//i[@class = 'astm-icon far fa-envelope']");
    this.CompassDropdown = page.locator("//li[@class='dropdown nav-item'][3]");
    this.DropdownPMPage = page.locator("//a[@class='d-flex align-items-center text-body dropdown-toggle nav-link']");
    this.MyAccount = page.locator("(//span[text()='My Account'])[2]");
    this.SinoutPMPage = page.locator("//button[text()='Sign Out']");
    this.SelectAenorAccount = page.locator("(//button[contains(text(),'Select')])[1]");
    this.ApiDropdown = page.locator("#account_menu_ipad");
    this.UsernameDropDown = page.locator("#account_menu_ipad .header-dropdown .user_name");
    this.UsernameDropDown_SignOut = page.locator("#account_menu_ipad_logout");
    this.CompassHomePage_SelectButton = page.locator(".accounts-content button");

     }
    }
