
import { Page, Locator } from '@playwright/test';

export class SpecBuilderPage {

    readonly selectAnAccountHeader: Locator;
readonly chooseBallotClosingDate: Locator;
readonly createButton: Locator;
readonly selectButtonOwensCorning: Locator;
readonly owensCorningHeader: Locator;
readonly committeeGroupRadioButton: Locator;
readonly createNewGroupButton: Locator;
readonly createNewGroupHeader: Locator;
readonly selectCommitteeDropdown: Locator;
readonly groupNameTextbox: Locator;
readonly spbLoader: Locator;
readonly deleteGroup: Locator;
readonly deleteCollaborationArea: Locator;
readonly memberLinkForGroup: Locator;
readonly memberTabTable: Locator;
readonly groupAdministratorDropdown: Locator;
readonly groupDescriptionTextbox: Locator;
readonly additionalMembersTextbox: Locator;
readonly uploadDraftsNoRadioBtn: Locator;
readonly uploadOptionsSectionHeader: Locator;
readonly createGroupButton: Locator;
readonly additionalMembersHeader: Locator;
readonly uploadSupportNo: Locator;
readonly accountLink: Locator;
readonly buttonSignOut: Locator;
readonly tokenExpiredHeader: Locator;
readonly cookieCloseButton: Locator;
readonly memberAsTab: Locator;
readonly addOrRemoveMembersBtn: Locator;
readonly addMemberArrow: Locator;
readonly removeMemberArrow: Locator;
readonly selectMember: Locator;
readonly disSelectMember: Locator;
readonly manage: Locator;
readonly selectGroup_editGroup: Locator;
readonly selectGroup_replaceDraft: Locator;
readonly selectSubGroup_replaceDraft: Locator;
readonly uploadDrafts: Locator;
readonly editGroup: Locator;
readonly manageEmailsBallotReminder: Locator;
readonly specBuilderAdmin: Locator;
readonly archivedGroups: Locator;
readonly restoreGroup: Locator;
readonly deleteArchiveGroup: Locator;
readonly delete: Locator;
readonly delete_ModalFooter: Locator;
readonly restoreGroupButton: Locator;
readonly parentGroupSelection: Locator;
readonly userAdministrator: Locator;
readonly userAdministratorButton: Locator;
readonly commentsSection: Locator;
readonly voteSection: Locator;
readonly affirmativeRadio: Locator;
readonly negativeRadio: Locator;
readonly abstainRadio: Locator;
readonly selectAll: Locator;
readonly selectAllRightArrow: Locator;
readonly selectAllLeftArrow: Locator;
readonly alertSaveVote: Locator;
readonly editCollaborationArea: Locator;
readonly spbLoadingIcon: Locator;
readonly home: Locator;
readonly calendarEvents: Locator;
readonly group: Locator;
readonly ballot: Locator;
readonly openBallot: Locator;
readonly voteSelection: Locator;
readonly roleReportSection: Locator;
readonly recentActivitiesWidgetCount: Locator;
readonly firstGroup: Locator;
readonly history: Locator;
readonly showAllCollaborationAreas: Locator;
readonly groupHistory: Locator;
readonly ballots: Locator;
readonly ballotReports: Locator;
readonly noBallotReportsFound: Locator;
readonly viewReport: Locator;
readonly viewReport_openBallot: Locator;
readonly csv: Locator;
readonly xlsx: Locator;
readonly ballotTitle: Locator;
readonly voteComment: Locator;
readonly saveVote: Locator;
readonly votingNote: Locator;
readonly externalGroupId: Locator;
readonly maxCount_externalGroupId: Locator;
readonly groupEmailDisplayName: Locator;
readonly saveGroup: Locator;
readonly manageDrafts: Locator;
readonly replaceDrafts: Locator;
readonly newCollaborationArea: Locator;
readonly newCollaborationAreaLink: Locator;
readonly committeeGroupRadioBtn: Locator;
readonly selectCommittee: Locator;
readonly uploadDrafts_Yes: Locator;
readonly uploadSupport_Yes: Locator;
readonly createCollaborationArea: Locator;
readonly collaborationAreaTitle: Locator;
readonly additionalMembersEmail: Locator;
readonly memberSearch: Locator;
readonly memberSelectDD: Locator;
readonly addMemberBTN: Locator;
readonly collaborationAdministrator: Locator;
readonly initialDraft_No: Locator;
readonly initialDraft_Yes: Locator;
readonly collaborationAreaNo: Locator;
readonly currentCollabArea: Locator;
readonly collaborationArea_Tab: Locator;
readonly scheduleOnlineMeeting: Locator;
readonly exportCSV: Locator;
readonly exportXLSX: Locator;
readonly selectButton_PlasticsPipeInstitute: Locator;
readonly manageButton: Locator;
readonly userReports: Locator;
readonly allUsersRadio: Locator;
readonly membersRadio: Locator;
readonly ballotRadio: Locator;
readonly registeredUserReport: Locator;
readonly applicationCode: Locator;
readonly footerHome: Locator;
readonly poweredByQuickStart: Locator;
readonly roleAll: Locator;
readonly userNameAll: Locator;
readonly ballotVoteElement: Locator;
readonly iframeBallotReport: Locator;
readonly searchValue: Locator;
readonly searchSearch: Locator;
readonly selectAllOption: Locator;
readonly officialVoter: Locator;
readonly abelsTerry: Locator;
readonly adhocTest: Locator;
readonly active: Locator;
readonly startDate: Locator;
readonly endDate: Locator;
readonly groupNameAll: Locator;
readonly groupStatusAll: Locator;
readonly showSelectedResults: Locator;
readonly manageBallotsTab: Locator;
readonly manageBallots_AllVoteReports: Locator;
readonly homeButton: Locator;
readonly manageEmails: Locator;
readonly manageEmailsNewBallot: Locator;
readonly selectBallotsGroup: Locator;
readonly isThisRecirculation_No: Locator;
readonly isThisRecirculation_Yes: Locator;
readonly selectBallottoRecirculateDropdown: Locator;
readonly selectBallottoRecirculateDropdownOptions: Locator;
readonly selectBallotToRecirculate: Locator;
readonly selectBallotToRecirculateNote: Locator;
readonly createNewBallot: Locator;
readonly leavePage: Locator;
readonly isThisARecirculation: Locator;
readonly isThisARecirculation_No_radio: Locator;
readonly isThisARecirculation_Yes_radio: Locator;
readonly homePage_ShowAllGroups: Locator;
readonly closeTitlePopUp: Locator;
readonly popUpTitle: Locator;
readonly voteLink: Locator;
readonly fOpenDate: Locator;
readonly fCloseDate: Locator;
readonly fCEventsGroupName: Locator;
readonly openDate: Locator;
readonly closeDate: Locator;
readonly cEventsGroupName: Locator;
readonly edit_draftComment: Locator;
readonly editComment: Locator;
readonly save: Locator;
readonly manageBallots: Locator;
readonly editBallotDetails: Locator;
readonly polls: Locator;
readonly editPoll: Locator;
readonly selectPoll: Locator;
readonly selectGroup_editBallots: Locator;
readonly selectSubGroup_editBallots: Locator;
readonly saveChanges: Locator;
readonly discussions: Locator;
readonly comment_discussions: Locator;

    constructor( page: Page) {
         this.selectAnAccountHeader = page.locator("//*[text()='Select an Account']");
  this.chooseBallotClosingDate = page.locator("//input[@id='rdp-form-control-closingDate']");
  this.createButton = page.locator("//button[contains(text(),'Create New Group')]");
  this.selectButtonOwensCorning = page.locator("//*[text()='Select']");
  this.owensCorningHeader = page.locator("//*[@class='banner-wrapper']//*[text()='Owens Corning']");
  this.committeeGroupRadioButton = page.locator("//input[@value='Committee Group']");
  this.createNewGroupButton = page.locator("//button[text()='Create New Collaboration Area']|//button[text()='Create New Group']");
  this.createNewGroupHeader = page.locator("//*[contains(text(),'Create New')]");
  this.selectCommitteeDropdown = page.locator("//select[@aria-label='Select Value']");
  this.groupNameTextbox = page.locator("[name='groupName']");
  this.spbLoader = page.locator("//div[@class='astm-spinner spinner-border']");
  this.deleteGroup = page.locator("//a[text()='Delete Group']");
  this.deleteCollaborationArea = page.locator("//a[text()='Delete Collaboration Area']");
  this.memberLinkForGroup = page.locator("text=Members");
  this.memberTabTable = page.locator("//*[@class='spec-member-table-wrapper']");
  this.groupAdministratorDropdown = page.locator("//label[starts-with(text(),'Collaboration Area')]//following-sibling::div//select |//label[starts-with(text(),'Group')]//following-sibling::div//select");
  this.groupDescriptionTextbox = page.locator("*[name='description'][class='form-control']");
  this.additionalMembersTextbox = page.locator("[name='additionalMembers']");
  this.uploadDraftsNoRadioBtn = page.locator("//*[text()='No, just Collaboration Area Administrator']/preceding-sibling::input[@name='uploadAllCan']|//*[text()='No, just Group Administrator']/preceding-sibling::input[@name='uploadAllCan']");
  this.uploadOptionsSectionHeader = page.locator("//*[text()='Upload Options']");
  this.createGroupButton = page.locator("//button[contains(text(),'Create')]");
  this.additionalMembersHeader = page.locator("//*[text()='Additional Members:']");
  this.uploadSupportNo = page.locator("//input[@name='uploadAllSupportCan' and @value='No']");
  this.accountLink = page.locator("text=Account");
  this.buttonSignOut = page.locator("//button[contains(.,'Sign out')]");
  this.tokenExpiredHeader = page.locator("//*[contains(text(), 'Token Expired')]");
  this.cookieCloseButton = page.locator("//div[@class='alert freeze-msg astm-alert ']//button");
  this.memberAsTab = page.locator("//a[text()='Members']");
  this.addOrRemoveMembersBtn = page.locator("//a[text()='Add/Remove Members']");
  this.addMemberArrow = page.locator("//button[@aria-label='Add member']");
  this.removeMemberArrow = page.locator("//button[@aria-label='Remove Member']");
  this.selectMember = page.locator("(//div[@class='select-wrapper'])[1]//option[1]");
  this.disSelectMember = page.locator("(//div[@class='select-wrapper'])[2]//option[1]");
  this.manage = page.locator("//button[text()='Manage']");
  this.selectGroup_editGroup = page.locator("//select[@title='Select Group to Edit']");
  this.selectGroup_replaceDraft = page.locator("//select[@title='Select a Group']");
  this.selectSubGroup_replaceDraft = page.locator("//select[@title='Select Draft']");
  this.uploadDrafts = page.locator("//button[text()='Upload Draft']");
  this.editGroup = page.locator("//a[text()='Edit Group']");
  this.manageEmailsBallotReminder = page.locator("//div[text()='Ballot Reminder']");
  this.specBuilderAdmin = page.locator("//a[text()='SpecBuilder Admin']");
  this.archivedGroups = page.locator("//a[text()='Archived Groups']");
  this.restoreGroup = page.locator("//div[text()='Restore ']//following-sibling::div//select[@title='Select Group']");
  this.deleteArchiveGroup = page.locator("//div[text()='Delete Archived ']//following-sibling::div//select[@title='Select Group']");
  this.delete = page.locator("//button[text()='Delete']");
  this.delete_ModalFooter = page.locator("//div[@class='modal-footer']//button[text()='Delete']");
  this.restoreGroupButton = page.locator("//button[text()='Restore ']");
  this.parentGroupSelection = page.locator("//select[@title='Select Group']");
  this.userAdministrator = page.locator("//a[text()='User Administration']");
  this.userAdministratorButton = page.locator("//button[text()='User Administration']");
  this.commentsSection = page.locator("//div[text()='Comments:']");
  this.voteSection = page.locator("//div[@class='radio-group']");
  this.affirmativeRadio = page.locator("//label[text()='Affirmative']//parent::div//input");
  this.negativeRadio = page.locator("//label[text()='Negative w/ Comment']//parent::div//input");
  this.abstainRadio = page.locator("//label[text()='Abstain']//parent::div//input");
  this.selectAll = page.locator("//a[@class='select-all']");
  this.selectAllRightArrow = page.locator("//button[@class='fas fa-caret-circle-right arrow-item']");
  this.selectAllLeftArrow = page.locator("//button[@class='fas fa-caret-circle-left arrow-item']");
  this.alertSaveVote = page.locator("//div[@role='alert']");
  this.editCollaborationArea = page.locator("//a[text()='Edit Collaboration Area']");
  this.spbLoadingIcon = page.locator("//div[@class='astm-spinner spinner-border']");
  this.home = page.locator("//span[text()='Home']");
  this.calendarEvents = page.locator("//a[text()='Calendar Events']");
  this.group = page.locator("//a[text()='Group']");
  this.ballot = page.locator("//a[text()='Ballots']");
  this.openBallot = page.locator("//a[text()='Open Ballot(s)']");
  this.voteSelection = page.locator("//td[2]//select[@class='form-control form-control-sm']");
  this.roleReportSection = page.locator("//table[@class='table astm-table table-striped table-striped--with-header rd-voter-table']//td[2]");
  this.recentActivitiesWidgetCount = page.locator("//span[text()='Recent Activity']//parent::div//following-sibling::div//tbody//tr");
  this.firstGroup = page.locator("//span[text()='My Groups']//parent::div//following-sibling::div//tbody//tr[1]");
  this.history = page.locator("//a[text()='History']");
  this.showAllCollaborationAreas = page.locator("//a[text()='Show All Collaboration Areas']");
  this.groupHistory = page.locator("//h3[text()=' History']");
  this.ballots = page.locator("//a[text()='Ballots']");
  this.ballotReports = page.locator("//a[text()='Ballot Reports']");
  this.noBallotReportsFound = page.locator("//div[text()='There are no reports at this time.']");
  this.viewReport = page.locator("//a[text()='View Report'][1]");
  this.viewReport_openBallot = page.locator("//span[text()='View Report']");
  this.csv = page.locator("//span[text()='Export CSV']");
  this.xlsx = page.locator("//span[text()='Export XLSX']");
  this.ballotTitle = page.locator("//table[@class='table astm-table table-striped table-striped--with-header']//td[2]//span");
  this.voteComment = page.locator("//textarea[@placeholder='Write your message here']");
  this.saveVote = page.locator("//button[text()='Save Vote']");
  this.votingNote = page.locator("//table[@class='table astm-table table-striped table-striped--with-header rd-voter-table']//tr[1]//td[5]");
  this.externalGroupId = page.locator("//input[@name='externalSystemID']");
  this.maxCount_externalGroupId = page.locator("//small[text()='Max 50 characters (']");
  this.groupEmailDisplayName = page.locator("//input[@name='groupEmailDisplayName']");
  this.saveGroup = page.locator("//button[text()='Save ']");
  this.manageDrafts = page.locator("//a[text()='Manage Drafts']");
  this.replaceDrafts = page.locator("//a[text()='Replace Drafts']");
  this.newCollaborationArea = page.locator("//button[text()='Create New Collaboration Area']");
  this.newCollaborationAreaLink = page.locator("//a[text()='New Collaboration Area']");
  this.committeeGroupRadioBtn = page.locator("//input[@value='Committee Group']");
  this.selectCommittee = page.locator("//div[@class='form-group']//select[@class='form-control']");
  this.uploadDrafts_Yes = page.locator("//input[@name='uploadAllCan' and @value='Yes']");
  this.uploadSupport_Yes = page.locator("//input[@name='uploadAllSupportCan' and @value='Yes']");
  this.createCollaborationArea = page.locator("//button[text()='Collaboration Area']");
  this.collaborationAreaTitle = page.locator("//input[@name='groupName']");
  this.additionalMembersEmail = page.locator("//textarea[@name='additionalMembers']");
  this.memberSearch = page.locator("//input[@name='searchMember']");
  this.memberSelectDD = page.locator("//p[@class='filtered-members']/parent::div/descendant::select");
  this.addMemberBTN = page.locator("//button[@aria-label='Add member']");
  this.collaborationAdministrator = page.locator("//select[@title='Select Collaboration Area Administrator']");
  this.initialDraft_No = page.locator("//input[@name='isUploadNow' and @value='No']");
  this.initialDraft_Yes = page.locator("//input[@name='isUploadNow' and @value='Yes']");
   this.collaborationAreaNo = page.locator("//div[@class='group-switcher-wrapper']//following-sibling::div[contains(@class,'title')]");
  this.currentCollabArea = page.locator("//select[@aria-label='Switch Group']");
  this.collaborationArea_Tab = page.locator("//a[text()='Collaboration Area']");
  this.scheduleOnlineMeeting = page.locator("//a[text()='Schedule Online Meeting']");
  this.exportCSV = page.locator("//span[text()='Export CSV']");
  this.exportXLSX = page.locator("//span[text()='Export XLSX']");
  this.selectButton_PlasticsPipeInstitute = page.locator("//span[text()='Plastics Pipe Institute']/parent::p/button");
  this.manageButton = page.locator("//button[text()='Manage']");
  this.userReports = page.locator("//a[text()='User Reports']");
  this.allUsersRadio = page.locator("//label[text()='All Users for Account']");
  this.membersRadio = page.locator("//label[text()='Members by Group']");
  this.ballotRadio = page.locator("//label[text()='Ballot Vote Activity Report']");
  this.registeredUserReport = page.locator("//span[text()='Registered User Report']");
  this.applicationCode = page.locator("(//div[text()='All'])[@data-automation-context='Application Code']");
  this.footerHome = page.locator("//li[@data-testid='test_home']");
  this.poweredByQuickStart = page.locator("//span[text()='Powered by QuickSight']");
  this.roleAll = page.locator("//div[@data-automation-context='Role' and text()='All']");
  this.userNameAll = page.locator("//div[@data-automation-context='User Name' and text()='All']");
  this.ballotVoteElement = page.locator("//span[text()='Ballot Vote Activity Report']");
  this.iframeBallotReport = page.locator("//iframe[@class='quicksight-embedding-iframe']");
  this.searchValue = page.locator("//input[@placeholder='Search value']");
  this.searchSearch = page.locator("//span[text()='Search']");
  this.selectAllOption = page.locator("//li[@data-automation-id='dropdown_select_all_search_result_entry']");
  this.officialVoter = page.locator("//li[@data-automation-context='Official Voter']");
  this.abelsTerry = page.locator("//li[@data-automation-context='Abels, Terry']");
  this.adhocTest = page.locator("//li[@data-automation-context='Adhoc Testing']");
  this.active = page.locator("//li[@data-automation-context='Active']");
  this.startDate = page.locator("(//input[@data-automation-id='date_picker_0'])[1]");
  this.endDate = page.locator("(//input[@data-automation-id='date_picker_0'])[2]");
  this.groupNameAll = page.locator("//div[@data-automation-context='Group Name' and text()='All']");
  this.groupStatusAll = page.locator("//div[@data-automation-context='Group Status' and text()='All']");
  this.showSelectedResults = page.locator("//span/p[text()='Show selected']");
  this.manageBallotsTab = page.locator("//a[@class='nav-link' and text()='Manage Ballots']");
  this.manageBallots_AllVoteReports = page.locator("//a[@href='/admins/ballot/vote-reports']");
  this.homeButton = page.locator(".home-nav-menu a");
  this.manageEmails = page.locator("//a[text()='Manage Emails']");
  this.manageEmailsNewBallot = page.locator("//div[text()='New Ballot']");
  this.selectBallotsGroup = page.locator("(//select[@class='form-control'])[2]");
  this.isThisRecirculation_No = page.locator("//input[@data-testid='recirculation-unchecked']");
  this.isThisRecirculation_Yes = page.locator("//input[@data-testid='recirculation-checked']");
  this.selectBallottoRecirculateDropdown = page.locator("//div[@data-testid='recirulation-title']/following::div/descendant::select");
  this.selectBallottoRecirculateDropdownOptions = page.locator("//div[@data-testid='recirulation-title']/following::div/descendant::select/option");
  this.selectBallotToRecirculate = page.locator("//select[@title='Select a Ballot']");
  this.selectBallotToRecirculateNote = page.locator("//small[text()='Note: A ballot must be closed to recirculate']");
  this.createNewBallot = page.locator("//button[text()='Create New Ballot']");
  this.leavePage = page.locator("//button[@class='btn astm-btn btn-secondary' and text()='Leave']");
  this.isThisARecirculation = page.locator("//div[@class='astm-type-heading--h6' and text()='Is this a recirculation?']");
  this.isThisARecirculation_No_radio = page.locator("//div[text()='Is this a recirculation?']//following-sibling::div//label[text()='No']//preceding-sibling::input");
  this.isThisARecirculation_Yes_radio = page.locator("//div[text()='Is this a recirculation?']//following-sibling::div//label[text()='Yes']//preceding-sibling::input");
  this.homePage_ShowAllGroups = page.locator("//a[@class='spec-link' and text()='Show All Groups']");
  this.closeTitlePopUp = page.locator("//button[text()='Close']");
  this.popUpTitle = page.locator("(//span[@class='text-sizing'])[1]");
  this.voteLink = page.locator("(//span[@class='text-sizing'])[2]");
  this.fOpenDate = page.locator("(//span[@class='text-sizing'])[2]");
  this.fCloseDate = page.locator("(//span[@class='text-sizing'])[3]");
  this.fCEventsGroupName = page.locator("(//span[@class='text-sizing'])[4]");
  this.openDate = page.locator("(//span[@class='text-sizing'])[3]");
  this.closeDate = page.locator("(//span[@class='text-sizing'])[4]");
  this.cEventsGroupName = page.locator("(//span[@class='text-sizing'])[5]");
  this.edit_draftComment = page.locator("//span[text()='Edit']");
  this.editComment = page.locator("//div[@role='textbox']");
  this.save = page.locator("//button[text()='Save']");
  this.manageBallots = page.locator("//a[text()='Manage Ballots']");
  this.editBallotDetails = page.locator("//a[text()='Edit Ballot Details']");
  this.polls = page.locator("//a[text()='Polls']");
  this.editPoll = page.locator("//a[text()='Edit Poll Details']");
  this.selectPoll = page.locator("//select[@title='Select Poll']");
  this.selectGroup_editBallots = page.locator("//select[@title='Select a Group']");
  this.selectSubGroup_editBallots = page.locator("//select[@title='Select Ballot']");
  this.saveChanges = page.locator("//button[text()='Save Changes']");
  this.discussions = page.locator("//a[text()='Discussions']");
  this.comment_discussions = page.locator("//div[@role='textbox']");



    }
}
